/**
 * Washington State City Data
 *
 * DATA SOURCES (all updated March 2025):
 * - population: U.S. Census Bureau, ACS 5-Year Estimates 2023, B01003_001E
 *               Released December 2024. api.census.gov/data/2023/acs/acs5
 * - medianHouseholdIncome: ACS 5-Year Estimates 2023, Table B19013
 *               Released December 2024. api.census.gov/data/2023/acs/acs5
 * - populationGrowthPct: (ACS 2023 pop − 2020 Decennial Census pop) / 2020 pop × 100
 *               Sources: api.census.gov/data/2023/acs/acs5 + /data/2020/dec/pl
 * - consultingFirmCount: County Business Patterns 2022, NAICS 5416
 *               Apportioned to cities by population share with urban density adjustment
 *               api.census.gov/data/2022/cbp
 * - smbCount: CBP 2022, NAICS 23,31-33,42,44-45,48-49,54,62,72 (5-249 employees, ~45% of total)
 *             Apportioned to cities by population share with urban density adjustment
 *             api.census.gov/data/2022/cbp
 * - businessMaturityPct: BLS Business Employment Dynamics, WA state 3-year survival rate
 *               2019-cohort tracked to 2022 (published 2023-2024). WA baseline = 61%.
 *               City-level adjusted by economic profile. bls.gov/bdm/
 * - ownerAge55PlusPct: ACS 5-Year Estimates 2023, Table B01001
 *               Age 55+ as % of total population. Released December 2024.
 *
 * SMB DEFINITION: 5–249 employees, NAICS 23/31-33/42/44-45/48-49/54/62/72
 *   Revenue proxy: ~$500K–$50M. Age: 3+ years (captured in businessMaturityPct)
 *
 * CITY TIER SYSTEM (by 2023 ACS population):
 *   Tier 1: 100k+  — Major hubs; severely oversaturated with consulting
 *   Tier 2: 60k–99k — Secondary metros; high competition
 *   Tier 3: 30k–59k — Mid-markets; OPTIMAL ZONE
 *   Tier 4: 15k–29k — Smaller markets; viable with caveats
 *   Tier 5: <15k   — Micro markets; limited SMB density
 *
 * lastUpdated: "2025-03"
 */

const DATA_METADATA = {
  lastUpdated: "2025-03",
  dataYear: 2023,
  sources: [
    {
      metric: "Population",
      source: "U.S. Census Bureau, ACS 5-Year Estimates 2023 (B01003_001E)",
      updateFrequency: "Annual (ACS 5-yr, released Dec)"
    },
    {
      metric: "Median Household Income",
      source: "U.S. Census Bureau, ACS 5-Year Estimates 2023, Table B19013",
      updateFrequency: "Annual (ACS 5-yr, released Dec)"
    },
    {
      metric: "Population Growth %",
      source: "ACS 2023 vs 2020 Decennial Census (P1_001N)",
      updateFrequency: "Annual vs fixed 2020 baseline"
    },
    {
      metric: "Consulting Firm Count",
      source: "County Business Patterns 2022, NAICS 5416 — city pop-share apportioned",
      updateFrequency: "Annual (CBP ~18-month lag)"
    },
    {
      metric: "SMB Count",
      source: "CBP 2022, NAICS 23/31-33/42/44-45/48-49/54/62/72 (5-249 emp) — city apportioned",
      updateFrequency: "Annual (CBP ~18-month lag)"
    },
    {
      metric: "Business Maturity %",
      source: "BLS Business Employment Dynamics, WA state 3-yr survival (61% baseline), city-adjusted",
      updateFrequency: "Annual (BLS BED)"
    },
    {
      metric: "Owner Age 55+ %",
      source: "U.S. Census Bureau, ACS 5-Year Estimates 2023, Table B01001",
      updateFrequency: "Annual (ACS 5-yr, released Dec)"
    }
  ]
};

const CITY_DATA = [

  // ─── TIER 1: Major Hubs (Avoid — Oversaturated) ──────────────
  {
    id: "seattle",
    name: "Seattle",
    county: "King",
    lat: 47.6062,
    lng: -122.3321,
    population: 741440,
    medianHouseholdIncome: 122000,
    populationGrowthPct: 0.6,
    consultingFirmCount: 1487,
    smbCount: 12000,
    businessMaturityPct: 59,
    ownerAge55PlusPct: 17.5,
    tier: 1,
    estimated: false,
    dataYear: 2023,
    notes: "Washington's tech and biotech capital, home to Amazon, Boeing, and a dense ecosystem of professional services firms. Despite enormous SMB volume, the market is saturated with Big 4, regional advisory, and boutique M&A firms. The cost of client acquisition here far exceeds that of any Tier 3 market — advisory margins are compressed and relationships are already claimed. Avoid as a standalone practice target."
  },
  {
    id: "bellevue",
    name: "Bellevue",
    county: "King",
    lat: 47.6101,
    lng: -122.2015,
    population: 151199,
    medianHouseholdIncome: 161000,
    populationGrowthPct: -0.4,
    consultingFirmCount: 253,
    smbCount: 2039,
    businessMaturityPct: 57,
    ownerAge55PlusPct: 19.9,
    tier: 1,
    estimated: false,
    dataYear: 2023,
    notes: "Microsoft and Amazon's corporate neighbor — the highest-income large city in WA. Consulting saturation is extreme, but the exit market for tech-adjacent SMBs (SaaS, managed services, fintech) is real and underserved by traditional advisory firms that lack tech sector expertise. Niche entry as a tech SMB exit specialist is viable."
  },
  {
    id: "spokane",
    name: "Spokane",
    county: "Spokane",
    lat: 47.6588,
    lng: -117.426,
    population: 229228,
    medianHouseholdIncome: 66000,
    populationGrowthPct: 0.1,
    consultingFirmCount: 199,
    smbCount: 3167,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 22.6,
    tier: 1,
    estimated: false,
    dataYear: 2023,
    notes: "Eastern Washington's regional hub anchored by healthcare, higher education, and logistics — a diverse SMB base with meaningful succession dynamics. The Spokane market is value-conscious ($66k median income) and relationship-driven; entry through the Spokane Chamber and regional CPA network is the correct play. Competition exists but is not organized around exit and succession advisory specifically."
  },
  {
    id: "tacoma",
    name: "Tacoma",
    county: "Pierce",
    lat: 47.2529,
    lng: -122.4443,
    population: 220482,
    medianHouseholdIncome: 84000,
    populationGrowthPct: 0.5,
    consultingFirmCount: 149,
    smbCount: 2562,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 20.8,
    tier: 1,
    estimated: false,
    dataYear: 2023,
    notes: "A port and manufacturing city with a large, diverse SMB base including logistics, food processing, and professional services. Income at the WA median supports standard fee structures. The market has established consulting presence but exit advisory remains underserved outside the downtown core. Pierce County banking relationships are the key referral channel."
  },
  {
    id: "vancouver",
    name: "Vancouver",
    county: "Clark",
    lat: 45.6387,
    lng: -122.6615,
    population: 192696,
    medianHouseholdIncome: 78000,
    populationGrowthPct: 0.9,
    consultingFirmCount: 198,
    smbCount: 2153,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 22.3,
    tier: 1,
    estimated: false,
    dataYear: 2023,
    notes: "Clark County's largest city, effectively part of the Portland-Vancouver metro and influenced by Oregon's lower tax environment. Many business owners here have cross-border financial considerations that complicate exit structuring — a genuine specialty niche. Consulting competition exists but is Portland-facing; a WA-specific advisory practice has clear differentiation."
  },
  {
    id: "kent",
    name: "Kent",
    county: "King",
    lat: 47.3809,
    lng: -122.2348,
    population: 135015,
    medianHouseholdIncome: 90000,
    populationGrowthPct: -1.2,
    consultingFirmCount: 102,
    smbCount: 1821,
    businessMaturityPct: 63,
    ownerAge55PlusPct: 17.5,
    tier: 1,
    estimated: false,
    dataYear: 2023,
    notes: "Boeing's supply chain heart — a dense corridor of aerospace manufacturing, logistics, and industrial services SMBs. Many are second-generation family businesses whose owners spent careers supplying Boeing and are now approaching exit with no succession plan. Fee capacity is adequate ($90k median); competition is low relative to SMB density once King County inflation is corrected."
  },
  {
    id: "everett",
    name: "Everett",
    county: "Snohomish",
    lat: 47.979,
    lng: -122.2021,
    population: 111083,
    medianHouseholdIncome: 82000,
    populationGrowthPct: 0.4,
    consultingFirmCount: 75,
    smbCount: 1235,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 20.9,
    tier: 1,
    estimated: false,
    dataYear: 2023,
    notes: "A Tier 1 city anchored by Boeing's commercial aircraft production and a growing port economy. The manufacturing ecosystem creates natural advisory demand — owners of aerospace suppliers, machine shops, and industrial distributors are aging into succession decisions. Income and SMB density both support a sustainable practice."
  },
  {
    id: "renton",
    name: "Renton",
    county: "King",
    lat: 47.4829,
    lng: -122.2171,
    population: 105279,
    medianHouseholdIncome: 97000,
    populationGrowthPct: -1.4,
    consultingFirmCount: 80,
    smbCount: 1420,
    businessMaturityPct: 63,
    ownerAge55PlusPct: 18.5,
    tier: 1,
    estimated: false,
    dataYear: 2023,
    notes: "Home to Boeing HQ and increasingly Amazon's logistics network. The industrial-to-tech transition is creating business ownership churn — companies being acquired, spun off, or reorganized. Owner demographics skew younger than typical Tier 1 cities due to Amazon's workforce, but the Boeing legacy businesses represent mature succession targets."
  },

  // ─── TIER 2: Secondary Metros (High Competition — Generally Avoid) 
  {
    id: "kirkland",
    name: "Kirkland",
    county: "King",
    lat: 47.6815,
    lng: -122.2087,
    population: 91614,
    medianHouseholdIncome: 144000,
    populationGrowthPct: -0.6,
    consultingFirmCount: 133,
    smbCount: 1071,
    businessMaturityPct: 57,
    ownerAge55PlusPct: 19.7,
    tier: 2,
    estimated: false,
    dataYear: 2023,
    notes: "Google's Puget Sound campus anchors high income ($144k) and sophisticated professional services. Entry is viable only with tech-sector differentiation."
  },
  {
    id: "redmond",
    name: "Redmond",
    county: "King",
    lat: 47.674,
    lng: -122.1215,
    population: 75721,
    medianHouseholdIncome: 162000,
    populationGrowthPct: 3.4,
    consultingFirmCount: 110,
    smbCount: 885,
    businessMaturityPct: 57,
    ownerAge55PlusPct: 15.3,
    tier: 2,
    estimated: false,
    dataYear: 2023,
    notes: "Microsoft's global headquarters creates WA's most concentrated per-capita income and consulting density market. Advisory for tech-adjacent SMBs (managed services, SaaS, tech staffing) is viable with specific sector expertise."
  },

  // ─── TIER 1: Major Hubs (Avoid — Oversaturated) ──────────────
  {
    id: "spokane-valley",
    name: "Spokane Valley",
    county: "Spokane",
    lat: 47.6732,
    lng: -117.2394,
    population: 105460,
    medianHouseholdIncome: 71000,
    populationGrowthPct: 2.4,
    consultingFirmCount: 76,
    smbCount: 1214,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 24.3,
    tier: 1,
    estimated: false,
    dataYear: 2023,
    notes: "Suburban Spokane; shares regional consulting market with core city"
  },

  // ─── TIER 2: Secondary Metros (High Competition — Generally Avoid) 
  {
    id: "sammamish",
    name: "Sammamish",
    county: "King",
    lat: 47.6163,
    lng: -122.0356,
    population: 66375,
    medianHouseholdIncome: 227000,
    populationGrowthPct: -1.6,
    consultingFirmCount: 48,
    smbCount: 776,
    businessMaturityPct: 57,
    ownerAge55PlusPct: 13.7,
    tier: 2,
    estimated: false,
    dataYear: 2023,
    notes: "One of the wealthiest residential cities in the nation ($227k median income) with a largely tech-worker bedroom community character. Despite extreme affluence, the commercial SMB base is thin — most wealth here is W-2 compensation from Redmond and Bellevue employers rather than business ownership. Prioritize neighboring markets for advisory practice development."
  },

  // ─── TIER 3: Mid-Markets (OPTIMAL — Low-Mod Competition) ─────
  {
    id: "bothell",
    name: "Bothell",
    county: "Snohomish/King",
    lat: 47.7623,
    lng: -122.2046,
    population: 48610,
    medianHouseholdIncome: 132000,
    populationGrowthPct: 0.9,
    consultingFirmCount: 24,
    smbCount: 396,
    businessMaturityPct: 59,
    ownerAge55PlusPct: 19.1,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "A biotech and pharmaceutical corridor (UW Bothell campus, Kenmore Air adjacent) with strong professional services SMBs and premium household income ($132k). Only 24 consulting firms for 48k people. The biotech ecosystem creates unique exit advisory opportunities — owners of life sciences service companies (CROs, testing labs, specialty distributors) are sophisticated about valuation but often lack M&A-specific advisors."
  },

  // ─── TIER 2: Secondary Metros (High Competition — Generally Avoid) 
  {
    id: "federal-way",
    name: "Federal Way",
    county: "King",
    lat: 47.3223,
    lng: -122.3126,
    population: 99232,
    medianHouseholdIncome: 82000,
    populationGrowthPct: -1.8,
    consultingFirmCount: 70,
    smbCount: 1160,
    businessMaturityPct: 63,
    ownerAge55PlusPct: 21.7,
    tier: 2,
    estimated: false,
    dataYear: 2023,
    notes: "A diverse, immigrant-rich city with a large retail and service SMB base — one of the most demographically complex markets in WA. Consulting competition is lower than the King County average once the density artifact is corrected. Income at the WA median supports standard fee structures. Entry through multicultural business associations and commercial banks serving the diverse community creates unique access."
  },
  {
    id: "bellingham",
    name: "Bellingham",
    county: "Whatcom",
    lat: 48.7519,
    lng: -122.4787,
    population: 92367,
    medianHouseholdIncome: 66000,
    populationGrowthPct: 1,
    consultingFirmCount: 91,
    smbCount: 1094,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 21.7,
    tier: 2,
    estimated: false,
    dataYear: 2023,
    notes: "Whatcom County's largest city with WWU, cross-border Canada trade, and a growing retail and outdoor economy."
  },
  {
    id: "kennewick",
    name: "Kennewick",
    county: "Benton",
    lat: 46.2112,
    lng: -119.1372,
    population: 84389,
    medianHouseholdIncome: 73000,
    populationGrowthPct: 0.6,
    consultingFirmCount: 52,
    smbCount: 805,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 22.2,
    tier: 2,
    estimated: false,
    dataYear: 2023,
    notes: "Tri-Cities anchor with the highest SMB count in the region. Agricultural services, food processing, construction, and retail form the SMB backbone. DOE Hanford adjacency creates a professional services layer. Best served as the center of a combined Tri-Cities territory with Richland and Pasco — combined that gives ~2,000+ SMBs with only ~110 consulting firms total."
  },
  {
    id: "yakima",
    name: "Yakima",
    county: "Yakima",
    lat: 46.6021,
    lng: -120.5059,
    population: 96810,
    medianHouseholdIncome: 59000,
    populationGrowthPct: -0.2,
    consultingFirmCount: 24,
    smbCount: 784,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 21.4,
    tier: 2,
    estimated: false,
    dataYear: 2023,
    notes: "Washington's agricultural processing hub and the center of the state's tree fruit industry. The SMB ecosystem includes food processors, agricultural input suppliers, cold storage operators, and farm equipment dealers — many in second or third-generation ownership with no formal succession infrastructure. Income at $59k is the binding constraint; success-fee structures work better than retainers here."
  },
  {
    id: "auburn",
    name: "Auburn",
    county: "King/Pierce",
    lat: 47.3073,
    lng: -122.2285,
    population: 85455,
    medianHouseholdIncome: 95000,
    populationGrowthPct: -2.1,
    consultingFirmCount: 68,
    smbCount: 999,
    businessMaturityPct: 63,
    ownerAge55PlusPct: 18.3,
    tier: 2,
    estimated: false,
    dataYear: 2023,
    notes: "A dense industrial and logistics corridor with aerospace manufacturing, warehousing, and retail serving the King-Pierce county border. Strong SMB density at 85k population with an established owner cohort. Income is well above WA median. Advisory access through Auburn Area Chamber and commercial lending relationships at local banks."
  },
  {
    id: "marysville",
    name: "Marysville",
    county: "Snohomish",
    lat: 48.0517,
    lng: -122.1771,
    population: 71570,
    medianHouseholdIncome: 100000,
    populationGrowthPct: 1.2,
    consultingFirmCount: 42,
    smbCount: 689,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 19.3,
    tier: 2,
    estimated: false,
    dataYear: 2023,
    notes: "A fast-growing Snohomish County city benefiting from Tulalip Tribes economic development, manufacturing expansion, and I-5 corridor logistics. Income at $100k and growing with only 42 consulting firms creates a legitimate first-mover window. The tribal gaming economy adjacent to Marysville creates unique business ownership structures worth understanding before approaching clients."
  },
  {
    id: "pasco",
    name: "Pasco",
    county: "Franklin",
    lat: 46.2396,
    lng: -119.1006,
    population: 78446,
    medianHouseholdIncome: 81000,
    populationGrowthPct: 1.7,
    consultingFirmCount: 18,
    smbCount: 611,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 13.5,
    tier: 2,
    estimated: false,
    dataYear: 2023,
    notes: "The fastest-growing of the Tri-Cities, driven by agricultural processing expansion and a young Hispanic workforce. SMB count is suppressed by the exclusion of agriculture (NAICS 11), which understates the true addressable market by 30–40%. Owners of food processing facilities, agricultural input distributors, and farm labor companies represent meaningful succession demand not visible in the raw count."
  },
  {
    id: "lakewood",
    name: "Lakewood",
    county: "Pierce",
    lat: 47.1718,
    lng: -122.5185,
    population: 63034,
    medianHouseholdIncome: 71000,
    populationGrowthPct: -0.9,
    consultingFirmCount: 31,
    smbCount: 529,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 22.9,
    tier: 2,
    estimated: false,
    dataYear: 2023,
    notes: "Pierce County's largest unincorporated city, heavily influenced by Joint Base Lewis-McChord — a government-adjacent economy with healthcare, retail, and professional services SMBs. Military-adjacent markets have unique ownership dynamics: many businesses are owned by retired servicemembers who are disciplined about planning but may have modest asset bases. Income at $71k is just above the value-sensitive threshold."
  },

  // ─── TIER 3: Mid-Markets (OPTIMAL — Low-Mod Competition) ─────
  {
    id: "shoreline",
    name: "Shoreline",
    county: "King",
    lat: 47.7557,
    lng: -122.3415,
    population: 59280,
    medianHouseholdIncome: 113000,
    populationGrowthPct: 1.1,
    consultingFirmCount: 36,
    smbCount: 693,
    businessMaturityPct: 59,
    ownerAge55PlusPct: 27.4,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "A dense inner suburb north of Seattle with the feel of a standalone city — diverse retail, healthcare services, and professional services SMBs. After correcting the King County consulting count artifact, this is a genuinely underserved market. High income ($113k) and a meaningful 55+ cohort (27%) make it one of the strongest Tier 3 targets. Entry through the Shoreline Chamber and Snohomish County CPA network."
  },

  // ─── TIER 2: Secondary Metros (High Competition — Generally Avoid) 
  {
    id: "richland",
    name: "Richland",
    county: "Benton",
    lat: 46.2857,
    lng: -119.2844,
    population: 61912,
    medianHouseholdIncome: 93000,
    populationGrowthPct: 2.2,
    consultingFirmCount: 38,
    smbCount: 590,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 22.7,
    tier: 2,
    estimated: false,
    dataYear: 2023,
    notes: "The most affluent of the Tri-Cities ($93k income) due to DOE and Department of Energy national lab employment. Government contractors and professional services firms represent a significant succession challenge — regulatory requirements constrain buyer eligibility. High technical workforce literacy means owners are more receptive to sophisticated advisory structures including ESAPs and ESOP alternatives."
  },

  // ─── TIER 3: Mid-Markets (OPTIMAL — Low-Mod Competition) ─────
  {
    id: "olympia",
    name: "Olympia",
    county: "Thurston",
    lat: 47.0379,
    lng: -122.9007,
    population: 55583,
    medianHouseholdIncome: 77000,
    populationGrowthPct: 0,
    consultingFirmCount: 35,
    smbCount: 479,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 23.9,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "Washington's state capital creates an economy dominated by government and government-adjacent professional services — lobbying, policy consulting, regulatory compliance. The commercial SMB advisory niche is distinct from these government consulting firms and effectively uncontested. High community visibility through the Thurston Chamber positions a practice quickly. Bundle with Lacey and Tumwater for a complete Thurston County territory."
  },
  {
    id: "lacey",
    name: "Lacey",
    county: "Thurston",
    lat: 47.0343,
    lng: -122.8231,
    population: 57088,
    medianHouseholdIncome: 87000,
    populationGrowthPct: 6.7,
    consultingFirmCount: 36,
    smbCount: 492,
    businessMaturityPct: 59,
    ownerAge55PlusPct: 25.3,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "Fastest-growing city in Washington at 6.7% population growth since 2020, driven by transit-oriented development and Thurston County's expanding healthcare and retail sectors. The growth wave is simultaneously creating new business formation and aging the incumbent owner cohort — a rare dual-pipeline opportunity. Only 36 consulting firms for 57k people. A Thurston County territory covering Lacey, Olympia, and Tumwater gives a combined 1,150+ SMB universe."
  },
  {
    id: "burien",
    name: "Burien",
    county: "King",
    lat: 47.4704,
    lng: -122.3468,
    population: 51331,
    medianHouseholdIncome: 91000,
    populationGrowthPct: -1.4,
    consultingFirmCount: 30,
    smbCount: 600,
    businessMaturityPct: 63,
    ownerAge55PlusPct: 21.9,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "A SeaTac-adjacent city with a genuinely diverse immigrant business community — Korean, Latino, and East African-owned businesses make up a meaningful share of the SMB base. After correcting the King County consulting count artifact, advisory competition is modest. Entry strategy should include the Highline Chamber and multilingual community banking relationships that already serve these owners. Income at $91k supports standard fee structures."
  },
  {
    id: "lynnwood",
    name: "Lynnwood",
    county: "Snohomish",
    lat: 47.8209,
    lng: -122.3151,
    population: 40953,
    medianHouseholdIncome: 76000,
    populationGrowthPct: 6.2,
    consultingFirmCount: 20,
    smbCount: 334,
    businessMaturityPct: 59,
    ownerAge55PlusPct: 24.2,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "Light rail extension to Lynnwood (opening 2024-2025) is transforming commercial character and driving 6.2% population growth. The transit-oriented development conversation is creating business transitions — owners near new station areas face buy-out offers and relocation decisions that require advisory support. Established retail and service SMBs with 20-30 year owner tenures are approaching natural succession windows simultaneously."
  },
  {
    id: "puyallup",
    name: "Puyallup",
    county: "Pierce",
    lat: 47.1854,
    lng: -122.2929,
    population: 42642,
    medianHouseholdIncome: 96000,
    populationGrowthPct: -0.8,
    consultingFirmCount: 18,
    smbCount: 303,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 21.2,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "Pierce County's commercial hub beyond Tacoma, known for the Washington State Fair and a diverse retail and agricultural fair economy. Strong income at $96k and established SMB base in retail, food service, and agricultural services. Owned businesses here tend to be multi-generational; family dynamics often complicate succession without professional guidance. Bundle with University Place and Bonney Lake for a full South Pierce territory."
  },
  {
    id: "edmonds",
    name: "Edmonds",
    county: "Snohomish",
    lat: 47.8107,
    lng: -122.3776,
    population: 42783,
    medianHouseholdIncome: 116000,
    populationGrowthPct: -0.2,
    consultingFirmCount: 21,
    smbCount: 349,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 30.3,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "The highest-conviction Tier 3 entry target in the dataset. Waterfront location, premium income ($116k), the highest age 55+ of any Tier 3 city (30.3%), and only 21 consulting firms. Succession wave is cresting now — not in five years. CPAs and wealth managers in the South Snohomish corridor are already seeing owner inquiries; becoming the recognized exit advisory specialist here is achievable within 12 months of territory activation."
  },
  {
    id: "bremerton",
    name: "Bremerton",
    county: "Kitsap",
    lat: 47.5673,
    lng: -122.6329,
    population: 44531,
    medianHouseholdIncome: 74000,
    populationGrowthPct: 2.4,
    consultingFirmCount: 32,
    smbCount: 332,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 17.1,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "Home to Puget Sound Naval Shipyard — WA's largest naval installation. The economy blends Navy contract services, retail, and healthcare. Geographic isolation across Puget Sound naturally limits consulting competition. Kitsap Transit's passenger ferry creates manageable access from Seattle. Owner demographics are younger than average (Navy influence) but the civilian business population is aging. The Kitsap Economic Development Alliance is the entry point."
  },
  {
    id: "wenatchee",
    name: "Wenatchee",
    county: "Chelan",
    lat: 47.4235,
    lng: -120.3103,
    population: 35502,
    medianHouseholdIncome: 70000,
    populationGrowthPct: 0,
    consultingFirmCount: 24,
    smbCount: 421,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 23.5,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "Central Washington's regional hub in the heart of the apple industry. The SMB ecosystem includes orchard equipment dealers, packinghouses, cold storage operators, agricultural lenders, and farm supply companies — many in generational transition right now. Only 24 consulting firms for 35k people. Geographic isolation from the west side limits competition. Position as the specialist for agricultural-adjacent business exits through the Washington State Tree Fruit Association."
  },
  {
    id: "mount-vernon",
    name: "Mount Vernon",
    county: "Skagit",
    lat: 48.4214,
    lng: -122.3343,
    population: 35312,
    medianHouseholdIncome: 73000,
    populationGrowthPct: 0.3,
    consultingFirmCount: 17,
    smbCount: 336,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 22.9,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "Skagit Valley's commercial center — the definitive agricultural hub advisory play in northern WA. Agricultural-adjacent SMBs are in generational transition. Only 17 competing firms. Top-5 Tier 3 entry target."
  },
  {
    id: "walla-walla",
    name: "Walla Walla",
    county: "Walla Walla",
    lat: 46.0646,
    lng: -118.343,
    population: 33766,
    medianHouseholdIncome: 65000,
    populationGrowthPct: -0.9,
    consultingFirmCount: 17,
    smbCount: 283,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 23.5,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "WA's wine capital has transformed from an agricultural town into a premium hospitality and wine industry hub. Wineries, tasting rooms, wine-adjacent hospitality businesses, and specialty food producers are concentrated here with significant asset values (vineyard real estate, brand equity, distribution) that dwarf what median income suggests. Position specifically as the wine industry and agri-tourism exit specialist — this vertical specialty commands premium positioning."
  },
  {
    id: "longview",
    name: "Longview",
    county: "Cowlitz",
    lat: 46.1382,
    lng: -122.9382,
    population: 37836,
    medianHouseholdIncome: 61000,
    populationGrowthPct: 0,
    consultingFirmCount: 7,
    smbCount: 263,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 26.5,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "The most underpenetrated advisory market in the Tier 3 dataset: only 7 consulting firms for 38k people. Timber, paper manufacturing, and port-adjacent industrial SMBs have complex succession needs and face industry consolidation pressure. ESOP structures work well for industrial businesses with loyal workforces. Income at $61k requires success-fee-weighted pricing, but deal sizes can be substantial in manufacturing exits."
  },
  {
    id: "university-place",
    name: "University Place",
    county: "Pierce",
    lat: 47.2151,
    lng: -122.5487,
    population: 34850,
    medianHouseholdIncome: 95000,
    populationGrowthPct: 0,
    consultingFirmCount: 14,
    smbCount: 248,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 24.9,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "An affluent Pierce County suburb ($95k median income) with a service and healthcare SMB base adjacent to the University of Washington Tacoma campus. Only 14 consulting firms. Best practiced as an anchor within a South Pierce County territory (with Puyallup and Bonney Lake) given the 248 SMB count is at the solo-practice floor. Premium income makes per-engagement economics strong."
  },
  {
    id: "issaquah",
    name: "Issaquah",
    county: "King",
    lat: 47.5301,
    lng: -122.0326,
    population: 39472,
    medianHouseholdIncome: 154000,
    populationGrowthPct: -1.4,
    consultingFirmCount: 32,
    smbCount: 390,
    businessMaturityPct: 59,
    ownerAge55PlusPct: 16.3,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "Home to Costco HQ and a high-income tech suburb ($154k median) with a significant service SMB base. After correcting the King County count artifact, advisory competition is more manageable. The affluent, tech-adjacent owner population is financially sophisticated — value proposition must go beyond basic valuation to include tax-efficient exit structuring, earn-out optimization, and buyer selection strategy."
  },
  {
    id: "seatac",
    name: "SeaTac",
    county: "King",
    lat: 47.4445,
    lng: -122.2987,
    population: 31143,
    medianHouseholdIncome: 77000,
    populationGrowthPct: -1,
    consultingFirmCount: 12,
    smbCount: 308,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 18.7,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "SeaTac's economy is dominated by Sea-Tac International Airport — hospitality, logistics, car rental, freight forwarding, and airport services. These businesses are primarily owner-operated with high revenues but thin margins compressed by airline contracts. Exit advisory here focuses on strategic buyer identification (often larger logistics or hospitality consolidators) rather than family succession. After correcting the count artifact, advisory competition is minimal."
  },

  // ─── TIER 4: Smaller Markets (Viable with Caveats) ───────────
  {
    id: "tumwater",
    name: "Tumwater",
    county: "Thurston",
    lat: 46.994,
    lng: -122.9087,
    population: 26519,
    medianHouseholdIncome: 94000,
    populationGrowthPct: 4.6,
    consultingFirmCount: 14,
    smbCount: 193,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 22.1,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "Thurston County's manufacturing and brewing hub — craft beverage, food processing, and industrial services. Part of the compelling Olympia-Lacey-Tumwater Thurston County territory."
  },

  // ─── TIER 3: Mid-Markets (OPTIMAL — Low-Mod Competition) ─────
  {
    id: "pullman",
    name: "Pullman",
    county: "Whitman",
    lat: 46.7298,
    lng: -117.1817,
    population: 31939,
    medianHouseholdIncome: 45000,
    populationGrowthPct: -2.9,
    consultingFirmCount: 5,
    smbCount: 180,
    businessMaturityPct: 59,
    ownerAge55PlusPct: 8.9,
    tier: 3,
    estimated: false,
    dataYear: 2023,
    notes: "Washington State University dominates this city — 30k+ students drive 85% of the local economy. The 8.9% age 55+ rate and $45k median income both reflect student demographics, not the actual business owner population. True M&A advisory demand comes from the small cohort of established non-university businesses (hospitality, retail, professional services) serving the permanent community. Treat as part of a larger Palouse region territory."
  },

  // ─── TIER 4: Smaller Markets (Viable with Caveats) ───────────
  {
    id: "moses-lake",
    name: "Moses Lake",
    county: "Grant",
    lat: 47.1301,
    lng: -119.2784,
    population: 25594,
    medianHouseholdIncome: 72000,
    populationGrowthPct: 1.8,
    consultingFirmCount: 7,
    smbCount: 194,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 18,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "Grant County's commercial hub with a distinctive dual economy: conventional agriculture (potatoes, corn, wheat) and a rapidly growing data center industry (Microsoft, Sabey, Dell — attracted by cheap Columbia Basin hydropower). The intersection of agricultural succession and tech-sector facility management creates unusual advisory opportunities. Only 7 consulting firms for 25k people."
  },
  {
    id: "ellensburg",
    name: "Ellensburg",
    county: "Kittitas",
    lat: 46.9965,
    lng: -120.5478,
    population: 18913,
    medianHouseholdIncome: 50000,
    populationGrowthPct: 1.3,
    consultingFirmCount: 9,
    smbCount: 182,
    businessMaturityPct: 59,
    ownerAge55PlusPct: 15.1,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "Central Washington University drives the economy — a college town with modest SMB activity primarily in retail, food service, and agricultural services supporting the broader Kittitas Valley. Age 55+ at 15% reflects student demographics. True advisory opportunity is limited to the non-university commercial sector; treat as an ancillary market within a Central WA territory."
  },
  {
    id: "port-angeles",
    name: "Port Angeles",
    county: "Clallam",
    lat: 48.1181,
    lng: -123.4307,
    population: 20087,
    medianHouseholdIncome: 62000,
    populationGrowthPct: 0.6,
    consultingFirmCount: 7,
    smbCount: 182,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 29.6,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "Olympic Peninsula's largest city, anchored by the ferry connection to Victoria BC and a declining timber economy supplemented by healthcare and retail. Business succession here often involves distressed situations — owners who need to exit as the industrial base contracts. Income at $62k is in the value-conscious range. Genuine geographic isolation means virtually no consulting competition from west-side firms."
  },
  {
    id: "oak-harbor",
    name: "Oak Harbor",
    county: "Island",
    lat: 48.2929,
    lng: -122.6432,
    population: 24396,
    medianHouseholdIncome: 72000,
    populationGrowthPct: -0.9,
    consultingFirmCount: 18,
    smbCount: 176,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 16.7,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "Whidbey Island Naval Air Station dominates — the local civilian economy consists of businesses serving the base population: retail, food service, healthcare, and personal services. Many owners are military veterans who value structured planning and understand organizational change. Ferry access creates minor friction but also limits competition. Income at $72k requires value-conscious fee structuring."
  },
  {
    id: "anacortes",
    name: "Anacortes",
    county: "Skagit",
    lat: 48.5126,
    lng: -122.6126,
    population: 17837,
    medianHouseholdIncome: 90000,
    populationGrowthPct: 1.1,
    consultingFirmCount: 8,
    smbCount: 154,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 38.1,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "Skagit County's port city — oil refinery (Tesoro/Marathon), Washington State Ferry hub, and a thriving maritime SMB ecosystem. Age 55+ at 38.1% is the highest of any Tier 4 city and well into \"urgent succession wave\" territory. Income at $90k supports professional fee structures. The refinery and maritime economy creates technical complexity in business exits that generalist advisors avoid — a real specialty opportunity. Bundle with Mount Vernon and Burlington."
  },
  {
    id: "centralia",
    name: "Centralia",
    county: "Lewis",
    lat: 46.7165,
    lng: -122.9543,
    population: 18457,
    medianHouseholdIncome: 52000,
    populationGrowthPct: 1.5,
    consultingFirmCount: 3,
    smbCount: 141,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 25.2,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "I-5 corridor commercial hub midway between Seattle and Portland. Outlet retail, manufacturing, and agricultural services form the SMB base. The region is economically challenged — income at $68k and a history of industrial contraction creates distressed succession scenarios alongside traditional planned exits. Low consulting presence (3 firms) makes this market effectively uncontested."
  },
  {
    id: "aberdeen",
    name: "Aberdeen",
    county: "Grays Harbor",
    lat: 46.9754,
    lng: -123.8157,
    population: 17040,
    medianHouseholdIncome: 52000,
    populationGrowthPct: 0.2,
    consultingFirmCount: 2,
    smbCount: 115,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 23.2,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "Grays Harbor's largest city with a timber heritage and challenging economic context — income at $57k and negative population trends. Business succession here tends to be distressed, with owners seeking exits from legacy timber-adjacent businesses as the industry contracts. Advisory focus on restructuring, asset sales, and succession-under-pressure scenarios rather than premium exit planning."
  },
  {
    id: "maple-valley",
    name: "Maple Valley",
    county: "King",
    lat: 47.3673,
    lng: -122.0487,
    population: 28121,
    medianHouseholdIncome: 148000,
    populationGrowthPct: 0.4,
    consultingFirmCount: 16,
    smbCount: 278,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 14.1,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "An affluent King County exurb ($148k income) with a retail and professional services SMB base. After correcting the density artifact, only 16 consulting firms. High income supports premium advisory fees. Part of a natural Maple Valley-Black Diamond-Covington territory."
  },
  {
    id: "covington",
    name: "Covington",
    county: "King",
    lat: 47.3607,
    lng: -122.1065,
    population: 20957,
    medianHouseholdIncome: 127000,
    populationGrowthPct: 0.9,
    consultingFirmCount: 10,
    smbCount: 207,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 17.6,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "A King County unincorporated area with bedroom community character and premium income ($127k). After correcting the consulting count artifact, competition is thin. Best served as part of a bundled Kent-Auburn-Covington corridor territory focused on the industrial and retail SMB base of the greater South King County market."
  },

  // ─── TIER 5: Micro Markets (Limited SMB Density) ─────────────
  {
    id: "poulsbo",
    name: "Poulsbo",
    county: "Kitsap",
    lat: 47.7348,
    lng: -122.646,
    population: 11962,
    medianHouseholdIncome: 96000,
    populationGrowthPct: -0.1,
    consultingFirmCount: 8,
    smbCount: 81,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 26,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "A Scandinavian-heritage Kitsap Peninsula community with boutique retail, marine services, and healthcare SMBs. Affluent character ($104k income) with a meaningful 55+ demographic. Part of a natural North Kitsap advisory territory with Silverdale and Kingston. Marine industry succession (boatyards, chandleries, charter operations) is a specific specialty opportunity."
  },
  {
    id: "kelso",
    name: "Kelso",
    county: "Cowlitz",
    lat: 46.1468,
    lng: -122.9057,
    population: 12697,
    medianHouseholdIncome: 59000,
    populationGrowthPct: -0.2,
    consultingFirmCount: 2,
    smbCount: 80,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 21.8,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Cowlitz County's smaller twin city to Longview, sharing the timber, port, and industrial economy. Combines with Longview to create a 50k-person combined market with only 9 consulting firms total. The combined Longview-Kelso territory is the most underpenetrated Tier 3-equivalent advisory market in the entire dataset."
  },

  // ─── TIER 4: Smaller Markets (Viable with Caveats) ───────────
  {
    id: "camas",
    name: "Camas",
    county: "Clark",
    lat: 45.5871,
    lng: -122.3996,
    population: 26779,
    medianHouseholdIncome: 140000,
    populationGrowthPct: 2.7,
    consultingFirmCount: 20,
    smbCount: 219,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 19.8,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "Clark County's affluent manufacturing hub, home to HP's laser jet division and Georgia-Pacific. High income ($140k) and a concentration of high-technology manufacturing SMBs in the supply chain. Only 20 consulting firms. The manufacturing-to-tech transition creates specific exit advisory demand — owners of precision manufacturing, electronics assembly, and industrial services companies are seeking successors or strategic buyers."
  },
  {
    id: "battle-ground",
    name: "Battle Ground",
    county: "Clark",
    lat: 45.7809,
    lng: -122.5296,
    population: 21293,
    medianHouseholdIncome: 100000,
    populationGrowthPct: 2.7,
    consultingFirmCount: 16,
    smbCount: 174,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 17.1,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "Clark County's fast-growing bedroom community (+17% population growth) with a young owner population establishing new businesses. The succession pipeline is long-term — today's new business formations are 10-15 year advisory relationships, not near-term exit mandates. Best served as part of a Clark County territory with Ridgefield and Camas."
  },
  {
    id: "washougal",
    name: "Washougal",
    county: "Clark",
    lat: 45.5832,
    lng: -122.3529,
    population: 16945,
    medianHouseholdIncome: 101000,
    populationGrowthPct: -0.6,
    consultingFirmCount: 12,
    smbCount: 126,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 20.3,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "A small Clark County city with manufacturing heritage (Pendleton Woolen Mills, other textile and industrial) transitioning toward Portland-area bedroom community status. Income at $108k reflects the affluent commuter population. Manufacturing succession is the specific advisory angle — owners of established industrial businesses face acquisition pressure from larger manufacturers."
  },
  {
    id: "bonney-lake",
    name: "Bonney Lake",
    county: "Pierce",
    lat: 47.1776,
    lng: -122.1779,
    population: 22776,
    medianHouseholdIncome: 132000,
    populationGrowthPct: 1.3,
    consultingFirmCount: 9,
    smbCount: 162,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 15.1,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "An affluent Pierce County bedroom community with premium income ($132k) and a retail and service SMB base — 9 consulting firms for 23k residents. Part of a natural Puyallup-Bonney Lake-Sumner corridor advisory territory."
  },

  // ─── TIER 5: Micro Markets (Limited SMB Density) ─────────────
  {
    id: "gig-harbor",
    name: "Gig Harbor",
    county: "Pierce",
    lat: 47.3296,
    lng: -122.5795,
    population: 12202,
    medianHouseholdIncome: 106000,
    populationGrowthPct: 1.4,
    consultingFirmCount: 5,
    smbCount: 79,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 36.6,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "The most compelling Tier 5 market in the dataset: 36.6% age 55+, $106k income, and only 5 consulting firms for 12k residents. The affluent waterfront community of retirees, medical professionals, and business owners provides premium fee capacity and urgent succession need. Best served as part of a South Kitsap territory with Port Orchard and Bremerton."
  },

  // ─── TIER 4: Smaller Markets (Viable with Caveats) ───────────
  {
    id: "monroe",
    name: "Monroe",
    county: "Snohomish",
    lat: 47.8553,
    lng: -121.9717,
    population: 19696,
    medianHouseholdIncome: 108000,
    populationGrowthPct: 0,
    consultingFirmCount: 9,
    smbCount: 146,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 16.5,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "Snohomish County's eastern gateway — a mix of agricultural services, retail, and light manufacturing along Highway 2. Income at $108k reflects the affluent exurban character. Part of a natural Highway 2 corridor territory with Sultan, Index, and Startup. Small but high-income SMB base."
  },
  {
    id: "arlington",
    name: "Arlington",
    county: "Snohomish",
    lat: 48.1651,
    lng: -122.1248,
    population: 20599,
    medianHouseholdIncome: 85000,
    populationGrowthPct: 3.7,
    consultingFirmCount: 10,
    smbCount: 168,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 20.3,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "Snohomish County's agricultural and industrial hub at the base of the Cascade foothills. Dairy farming support services, manufacturing, and retail form the SMB base. Income at $99k and only 10 consulting firms. The Stillaguamish Valley agricultural economy is entering generational transition."
  },
  {
    id: "mukilteo",
    name: "Mukilteo",
    county: "Snohomish",
    lat: 47.9465,
    lng: -122.304,
    population: 21312,
    medianHouseholdIncome: 123000,
    populationGrowthPct: -1,
    consultingFirmCount: 11,
    smbCount: 174,
    businessMaturityPct: 59,
    ownerAge55PlusPct: 29.2,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "A premium Puget Sound waterfront community adjacent to Paine Field (Boeing's secondary field) with extremely high income ($123k) and a 29.2% age 55+ population — the best succession timing + income combination among Tier 4 cities. Only 11 consulting firms. Boeing-adjacent manufacturing services businesses represent unique succession complexity around government contract transferability."
  },
  {
    id: "mill-creek",
    name: "Mill Creek",
    county: "Snohomish",
    lat: 47.8609,
    lng: -122.204,
    population: 20846,
    medianHouseholdIncome: 122000,
    populationGrowthPct: -0.4,
    consultingFirmCount: 10,
    smbCount: 170,
    businessMaturityPct: 59,
    ownerAge55PlusPct: 21.1,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "A Snohomish County planned community with premium income ($122k), high home ownership, and a retail/professional services SMB base. Only 10 consulting firms. The community is mature — established businesses averaging 15-20 years old are in natural exit windows. Part of an Everett-Lynnwood-Mill Creek corridor territory."
  },
  {
    id: "port-orchard",
    name: "Port Orchard",
    county: "Kitsap",
    lat: 47.5404,
    lng: -122.6329,
    population: 16398,
    medianHouseholdIncome: 81000,
    populationGrowthPct: 5.2,
    consultingFirmCount: 11,
    smbCount: 111,
    businessMaturityPct: 59,
    ownerAge55PlusPct: 19,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "Kitsap County seat across from Bremerton, with retail, healthcare services, and government-adjacent businesses. Income at $91k is solid. The broader South Kitsap market (Port Orchard, Bremerton, Gig Harbor) creates a natural combined advisory territory with the peninsula's geographic isolation providing competitive protection."
  },
  {
    id: "lynden",
    name: "Lynden",
    county: "Whatcom",
    lat: 48.9492,
    lng: -122.4529,
    population: 16025,
    medianHouseholdIncome: 95000,
    populationGrowthPct: 1.8,
    consultingFirmCount: 12,
    smbCount: 146,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 24.7,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "A tight-knit agricultural and Dutch-heritage community in northern Whatcom County near the Canadian border. The SMB base is anchored by dairy farming support services, food processing, retail, and construction. Family business succession here is culturally embedded — generational transitions are common but often poorly structured. Income at $95k supports standard advisory fees. The Lynden Chamber is a genuine community institution."
  },
  {
    id: "ferndale",
    name: "Ferndale",
    county: "Whatcom",
    lat: 48.8465,
    lng: -122.602,
    population: 15447,
    medianHouseholdIncome: 84000,
    populationGrowthPct: 2.7,
    consultingFirmCount: 12,
    smbCount: 141,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 19.4,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "Whatcom County's industrial anchor — refineries (BP Cherry Point, adjacent), manufacturing, and port services. Owner demographics are skewing older and the industrial sector is consolidating. Exit advisory with a focus on industrial asset valuation and strategic buyer identification is the right positioning. Only 12 consulting firms despite meaningful industrial SMB activity."
  },
  {
    id: "sunnyside",
    name: "Sunnyside",
    county: "Yakima",
    lat: 46.3239,
    lng: -119.9979,
    population: 16329,
    medianHouseholdIncome: 53000,
    populationGrowthPct: -0.3,
    consultingFirmCount: 3,
    smbCount: 102,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 14.5,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "A Yakima Valley agricultural processing community — fruit packing, cold storage, and agricultural services. Only 3 consulting firms for 16k residents. Income at $62k is value-conscious but agricultural businesses here often have asset values that exceed income metrics. Part of a Yakima Valley sub-regional territory."
  },

  // ─── TIER 5: Micro Markets (Limited SMB Density) ─────────────
  {
    id: "east-wenatchee",
    name: "East Wenatchee",
    county: "Douglas",
    lat: 47.4176,
    lng: -120.2854,
    population: 14114,
    medianHouseholdIncome: 81000,
    populationGrowthPct: -0.3,
    consultingFirmCount: 2,
    smbCount: 83,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 20.3,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Douglas County's commercial extension of Wenatchee across the Columbia River. Part of the Wenatchee MSA advisory territory — the same advisory positioning covers both communities effectively."
  },
  {
    id: "snoqualmie",
    name: "Snoqualmie",
    county: "King",
    lat: 47.529,
    lng: -121.8276,
    population: 13750,
    medianHouseholdIncome: 198000,
    populationGrowthPct: -2.6,
    consultingFirmCount: 15,
    smbCount: 124,
    businessMaturityPct: 63,
    ownerAge55PlusPct: 9.7,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "An affluent King County exurb ($198k income) near the Snoqualmie Falls tourist attraction. Very young demographic (9.7% age 55+) reflects recent tech-worker family migration. Business succession is a decade away for most current SMBs. High income is the primary asset for advisory engagement economics when opportunities do arise."
  },
  {
    id: "enumclaw",
    name: "Enumclaw",
    county: "King",
    lat: 47.2017,
    lng: -121.9914,
    population: 12663,
    medianHouseholdIncome: 117000,
    populationGrowthPct: 1,
    consultingFirmCount: 14,
    smbCount: 114,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 27.4,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "A rural King County community with agricultural, equestrian, and timber economic character. Income at $92k reflects the affluent rural owner profile. Only 14 consulting firms. Part of a natural rural King County advisory territory with Black Diamond and Auburn."
  },
  {
    id: "woodinville",
    name: "Woodinville",
    county: "King",
    lat: 47.7548,
    lng: -122.1637,
    population: 13440,
    medianHouseholdIncome: 159000,
    populationGrowthPct: 2.8,
    consultingFirmCount: 15,
    smbCount: 121,
    businessMaturityPct: 59,
    ownerAge55PlusPct: 19.5,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Wine country in King County's northeast — a concentration of wineries, tasting rooms, and premium retail with extremely high income ($159k). The wine industry creates unique succession advisory opportunities (vineyard acquisition, brand exit, hospitality business sales). Only 15 consulting firms for a very affluent market. Wine industry exit specialty positioning is the right entry play."
  },

  // ─── TIER 4: Smaller Markets (Viable with Caveats) ───────────
  {
    id: "mountlake-terrace",
    name: "Mountlake Terrace",
    county: "Snohomish",
    lat: 47.7887,
    lng: -122.3054,
    population: 21419,
    medianHouseholdIncome: 101000,
    populationGrowthPct: 0.6,
    consultingFirmCount: 11,
    smbCount: 175,
    businessMaturityPct: 61,
    ownerAge55PlusPct: 24.4,
    tier: 4,
    estimated: false,
    dataYear: 2023,
    notes: "A dense inner suburb at the Snohomish-King county border with strong transit access (Light Rail). Income at $87k and a diverse retail/professional services SMB base. Only 11 consulting firms. Benefits from proximity to both Lynnwood and Shoreline market reach."
  },

  // ─── TIER 5: Micro Markets (Limited SMB Density) ─────────────
  {
    id: "ridgefield",
    name: "Ridgefield",
    county: "Clark",
    lat: 45.814,
    lng: -122.7395,
    population: 12576,
    medianHouseholdIncome: 118000,
    populationGrowthPct: 21.9,
    consultingFirmCount: 2,
    smbCount: 94,
    businessMaturityPct: 59,
    ownerAge55PlusPct: 17.4,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Clark County's fastest-growing suburb with recent industrial development and a young business formation wave. Exit advisory timing is early — businesses established in the last 5-10 years are not yet ready for succession. Best approached as part of a Clark County portfolio for future pipeline development."
  },
  {
    id: "sumner",
    name: "Sumner",
    county: "Pierce",
    lat: 47.2029,
    lng: -122.2315,
    population: 10674,
    medianHouseholdIncome: 98000,
    populationGrowthPct: 0.5,
    consultingFirmCount: 4,
    smbCount: 69,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 20,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "A Pierce County logistics hub with berry processing, warehousing, and light industrial SMBs. Only 4 consulting firms for 10k residents. The logistics and food processing sectors are consolidating — owner exits often occur through strategic acquisition rather than family succession. Income at $96k supports solid fee structures."
  },
  {
    id: "orting",
    name: "Orting",
    county: "Pierce",
    lat: 47.1004,
    lng: -122.2073,
    population: 8957,
    medianHouseholdIncome: 121000,
    populationGrowthPct: -0.9,
    consultingFirmCount: 3,
    smbCount: 58,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 14.6,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "A small Pierce County community in the Puyallup River valley with agricultural and residential character. The Rainier lahar risk zone adds unusual property risk considerations to business valuations — advisors must understand this context. Small market; part of a broader South Pierce County territory."
  },
  {
    id: "north-bend",
    name: "North Bend",
    county: "King",
    lat: 47.4957,
    lng: -121.7873,
    population: 7745,
    medianHouseholdIncome: 181000,
    populationGrowthPct: 3.8,
    consultingFirmCount: 2,
    smbCount: 70,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 17.8,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "A small King County community near Snoqualmie Pass with high income ($181k) and a tourism/retail SMB base. Geographic character (gateway to the Cascades) shapes the business ecosystem — outdoor recreation, hospitality, and retail serve the pass traffic. Small market; part of a natural Highway 2 corridor territory."
  },
  {
    id: "snohomish",
    name: "Snohomish",
    county: "Snohomish",
    lat: 47.9129,
    lng: -122.0987,
    population: 10177,
    medianHouseholdIncome: 85000,
    populationGrowthPct: 0.5,
    consultingFirmCount: 5,
    smbCount: 75,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 28.2,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "An antique district and small-town retail hub in Snohomish County with a 55+ population at 28% and income at $85k. The antique and specialty retail SMBs here often have lifestyle business character — owners who built businesses around personal collections or expertise. Succession for these businesses requires specialized buyer matching."
  },
  {
    id: "shelton",
    name: "Shelton",
    county: "Mason",
    lat: 47.2152,
    lng: -123.1006,
    population: 10619,
    medianHouseholdIncome: 61000,
    populationGrowthPct: 2.4,
    consultingFirmCount: 2,
    smbCount: 55,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 17.3,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Mason County's county seat with a timber and oyster industry heritage transitioning to a rural retail and healthcare economy. Income at $74k is in the standard range. The timber industry's decline has created a generation of business owners whose industrial businesses need succession planning. Only 2 consulting firms."
  },
  {
    id: "port-townsend",
    name: "Port Townsend",
    county: "Jefferson",
    lat: 48.117,
    lng: -122.7599,
    population: 10290,
    medianHouseholdIncome: 60000,
    populationGrowthPct: 1.4,
    consultingFirmCount: 8,
    smbCount: 97,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 49.3,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "A Victorian seaport with an arts, maritime, and tourism economy. Age 55+ at 49.3% is the third-highest in the dataset — an extreme succession demographic. Income at $60k is in the value-conscious range, but the unique maritime and arts business ecosystem creates specialty exit advisory opportunities (boatbuilding businesses, gallery-hospitality combinations, maritime services companies) that command premium positioning."
  },
  {
    id: "sequim",
    name: "Sequim",
    county: "Clallam",
    lat: 48.0795,
    lng: -123.1013,
    population: 8130,
    medianHouseholdIncome: 53000,
    populationGrowthPct: 1.3,
    consultingFirmCount: 3,
    smbCount: 67,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 50.6,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "A true retirement destination on the Olympic Peninsula's \"Banana Belt.\" Age 55+ at 50.6% is the second-highest in WA. Many business owners are retirees from other markets who established lifestyle businesses — wineries, lavender farms, boutique retail, professional services. Income at $53k is constrained, but Sequim is best approached as a satellite market within a broader Olympic Peninsula territory."
  },
  {
    id: "burlington",
    name: "Burlington",
    county: "Skagit",
    lat: 48.4742,
    lng: -122.3279,
    population: 9637,
    medianHouseholdIncome: 74000,
    populationGrowthPct: 5.3,
    consultingFirmCount: 4,
    smbCount: 83,
    businessMaturityPct: 59,
    ownerAge55PlusPct: 23.5,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Skagit Valley's retail hub adjacent to the Premium Outlets, with agricultural equipment, food processing, and retail SMBs. Only 4 consulting firms. Part of the natural Skagit County cluster with Mount Vernon and Anacortes. Agricultural transition dynamics create the primary advisory demand."
  },
  {
    id: "sedro-woolley",
    name: "Sedro-Woolley",
    county: "Skagit",
    lat: 48.5034,
    lng: -122.2365,
    population: 12633,
    medianHouseholdIncome: 72000,
    populationGrowthPct: 1.7,
    consultingFirmCount: 6,
    smbCount: 109,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 20.8,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Rural Skagit County with a timber heritage, industrial services, and agricultural support economy. Income at $82k is above the value-sensitive threshold. Part of a natural Skagit County territory with Mount Vernon and Burlington."
  },
  {
    id: "blaine",
    name: "Blaine",
    county: "Whatcom",
    lat: 48.9935,
    lng: -122.7465,
    population: 5982,
    medianHouseholdIncome: 82000,
    populationGrowthPct: 1.7,
    consultingFirmCount: 1,
    smbCount: 55,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 33,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "A US-Canada border community whose economy is heavily dependent on cross-border trade, duty-free retail, and marine services. Business owners here have complex Canada-US ownership and tax considerations that generalist advisors aren't equipped to handle. Minimal consulting competition makes this an opportunity for a specialist with cross-border transaction experience."
  },
  {
    id: "chelan",
    name: "Chelan",
    county: "Chelan",
    lat: 47.8373,
    lng: -120.0216,
    population: 4314,
    medianHouseholdIncome: 72000,
    populationGrowthPct: 2.2,
    consultingFirmCount: 3,
    smbCount: 46,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 32.5,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Lake Chelan resort and wine country — a concentration of wineries, resort hospitality, and recreational marine businesses. Age 55+ at 32.5% is elevated; income at $72k is value-sensitive. Lifestyle business exits (wineries, resorts, marinas) require specialized buyer matching for qualified purchasers who want to acquire a lifestyle, not just an income stream."
  },
  {
    id: "leavenworth",
    name: "Leavenworth",
    county: "Chelan",
    lat: 47.5957,
    lng: -120.6614,
    population: 2676,
    medianHouseholdIncome: 75000,
    populationGrowthPct: 18.3,
    consultingFirmCount: 2,
    smbCount: 29,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 26.6,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "A Bavarian-themed tourist destination with a concentrated hospitality and retail SMB base. Tourism businesses have specific exit valuation challenges — revenue seasonality, brand-dependent goodwill, and lifestyle buyer profiles. Small market; best approached as part of a Chelan County territory anchored in Wenatchee."
  },
  {
    id: "cashmere",
    name: "Cashmere",
    county: "Chelan",
    lat: 47.5162,
    lng: -120.4704,
    population: 3263,
    medianHouseholdIncome: 64000,
    populationGrowthPct: 0.5,
    consultingFirmCount: 2,
    smbCount: 35,
    businessMaturityPct: 64,
    ownerAge55PlusPct: 30.7,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "A small Chelan County apple-growing community with orchards, packing houses, and agricultural retail. Income at $64k and age 55+ at 30.7% create a specific agricultural succession advisory opportunity. Part of a Wenatchee-Chelan County territory."
  },
  {
    id: "ephrata",
    name: "Ephrata",
    county: "Grant",
    lat: 47.3176,
    lng: -119.5501,
    population: 8493,
    medianHouseholdIncome: 70000,
    populationGrowthPct: 0.2,
    consultingFirmCount: 2,
    smbCount: 58,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 18.6,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Grant County's county seat with an agricultural economy — wheat, potatoes, and precision agriculture. Only 2 consulting firms. Income at $70k supports standard fees. Columbia Basin irrigation system has driven agricultural business formation for 70+ years; many of these businesses are now in second or third generation ownership."
  },
  {
    id: "quincy",
    name: "Quincy",
    county: "Grant",
    lat: 47.234,
    lng: -119.8524,
    population: 7922,
    medianHouseholdIncome: 80000,
    populationGrowthPct: 5,
    consultingFirmCount: 2,
    smbCount: 55,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 13.2,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Grant County's fastest-growing city due to the data center boom — Microsoft, Sabey, and Dell are attracted by cheap Columbia Basin hydropower. The intersection of traditional agricultural succession and tech-sector facility management creates an unusual advisory landscape. Only 2 consulting firms for a city that now attracts significant capital investment."
  },
  {
    id: "othello",
    name: "Othello",
    county: "Adams",
    lat: 46.8254,
    lng: -119.1724,
    population: 8699,
    medianHouseholdIncome: 66000,
    populationGrowthPct: 1.8,
    consultingFirmCount: 2,
    smbCount: 60,
    businessMaturityPct: 63,
    ownerAge55PlusPct: 9.1,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "An Adams County agricultural community with potato processing, vegetable packing, and farm services. Income at $57k and very young demographics (9.1% age 55+) reflect the agricultural immigrant workforce. Advisory opportunity is long-term. The agricultural processing sector is consolidating nationally — strategic acquisition opportunities may arise independently of owner retirement."
  },
  {
    id: "toppenish",
    name: "Toppenish",
    county: "Yakima",
    lat: 46.3762,
    lng: -120.3082,
    population: 8746,
    medianHouseholdIncome: 68000,
    populationGrowthPct: -1.2,
    consultingFirmCount: 2,
    smbCount: 54,
    businessMaturityPct: 63,
    ownerAge55PlusPct: 15.1,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "A Yakima Valley agricultural community with the Yakama Nation's economic presence creating a distinctive dual business ecosystem. Income at $68k and a young demographic limit near-term advisory opportunity. The Yakama Nation tribal economy represents specialized advisory territory requiring specific expertise in tribal business law and succession."
  },
  {
    id: "grandview",
    name: "Grandview",
    county: "Yakima",
    lat: 46.2525,
    lng: -119.9021,
    population: 11042,
    medianHouseholdIncome: 60000,
    populationGrowthPct: 1.2,
    consultingFirmCount: 2,
    smbCount: 69,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 12.2,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Yakima Valley's agricultural processing community with food packing, cold storage, and agricultural input businesses. Income at $60k and a very young demographic (12.2% age 55+) make this a long-term rather than near-term advisory market. Part of a Yakima Valley territory anchored in Yakima or Kennewick."
  },
  {
    id: "selah",
    name: "Selah",
    county: "Yakima",
    lat: 46.6554,
    lng: -120.531,
    population: 8301,
    medianHouseholdIncome: 75000,
    populationGrowthPct: 1.8,
    consultingFirmCount: 2,
    smbCount: 52,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 18.6,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "A Yakima Valley community directly north of Yakima with fruit processing, retail, and healthcare services. Shares Yakima's advisory market dynamics. Income at $78k is close to WA median. Part of a Yakima-Selah combined territory."
  },
  {
    id: "prosser",
    name: "Prosser",
    county: "Benton",
    lat: 46.2093,
    lng: -119.7681,
    population: 6213,
    medianHouseholdIncome: 66000,
    populationGrowthPct: 2.5,
    consultingFirmCount: 3,
    smbCount: 46,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 20.7,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Benton County wine country hub with wineries, agricultural services, and food processing. Income at $80k is near WA median. The wine industry's maturation is creating succession demand — winery founders who built brands in the 1990s-2000s are approaching retirement. Small market but part of a natural Tri-Cities wine country territory."
  },
  {
    id: "goldendale",
    name: "Goldendale",
    county: "Klickitat",
    lat: 45.8218,
    lng: -120.8237,
    population: 3458,
    medianHouseholdIncome: 42000,
    populationGrowthPct: 0.1,
    consultingFirmCount: 2,
    smbCount: 25,
    businessMaturityPct: 64,
    ownerAge55PlusPct: 35.8,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Klickitat County seat with wind energy development, agriculture, and rural retail. Income at $42k is below the fee capacity floor. Wind energy companies are consolidating — land lease businesses and energy service companies represent advisory opportunities outside the traditional SMB definition."
  },
  {
    id: "white-salmon",
    name: "White Salmon",
    county: "Klickitat",
    lat: 45.7254,
    lng: -121.4893,
    population: 2533,
    medianHouseholdIncome: 73000,
    populationGrowthPct: 1.9,
    consultingFirmCount: 2,
    smbCount: 19,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 38.4,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "A small Klickitat County community in the Columbia Gorge wine and outdoor recreation corridor. Income at $73k is adequate. Very small market — part of a broader Gorge territory."
  },
  {
    id: "chehalis",
    name: "Chehalis",
    county: "Lewis",
    lat: 46.6626,
    lng: -122.9634,
    population: 7536,
    medianHouseholdIncome: 68000,
    populationGrowthPct: 1.3,
    consultingFirmCount: 1,
    smbCount: 57,
    businessMaturityPct: 63,
    ownerAge55PlusPct: 20.8,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Lewis County hub; I-5 corridor distribution/retail SMBs, mature base, near-zero consulting"
  },
  {
    id: "ocean-shores",
    name: "Ocean Shores",
    county: "Grays Harbor",
    lat: 46.9782,
    lng: -124.1582,
    population: 7076,
    medianHouseholdIncome: 63000,
    populationGrowthPct: 5.4,
    consultingFirmCount: 1,
    smbCount: 48,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 62.3,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "An extreme retirement destination on Grays Harbor's coast with the highest age 55+ (62.3%) in the dataset. Income at $63k limits fee capacity. The vacation home and lifestyle business economy creates specific advisory dynamics — owners of vacation rental businesses, coastal hospitality operations, and resort retail represent the primary advisory opportunity. Very small standalone market."
  },
  {
    id: "montesano",
    name: "Montesano",
    county: "Grays Harbor",
    lat: 46.9826,
    lng: -123.6035,
    population: 4157,
    medianHouseholdIncome: 66000,
    populationGrowthPct: 0.5,
    consultingFirmCount: 1,
    smbCount: 28,
    businessMaturityPct: 63,
    ownerAge55PlusPct: 29.3,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Grays Harbor county seat with government services, timber heritage, and retail. Income at $80k and minimal consulting competition. Part of a broader Grays Harbor territory anchored in Aberdeen."
  },
  {
    id: "omak",
    name: "Omak",
    county: "Okanogan",
    lat: 48.4115,
    lng: -119.5279,
    population: 4931,
    medianHouseholdIncome: 76000,
    populationGrowthPct: 1.5,
    consultingFirmCount: 1,
    smbCount: 42,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 23.8,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Okanogan County's commercial hub with agriculture, timber, and outdoor recreation. Income at $62k is value-conscious. The Colville Indian Reservation's economic presence creates a distinctive advisory context — tribal and non-tribal business interrelations are common. Only 1 consulting firm."
  },
  {
    id: "colville",
    name: "Colville",
    county: "Stevens",
    lat: 48.5451,
    lng: -117.904,
    population: 4979,
    medianHouseholdIncome: 49000,
    populationGrowthPct: 1.3,
    consultingFirmCount: 2,
    smbCount: 30,
    businessMaturityPct: 64,
    ownerAge55PlusPct: 32,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Stevens County seat in northeastern WA — timber, agriculture, and outdoor recreation. Income at $49k is below the fee capacity floor for standard advisory retainers. Genuine geographic isolation limits competition but also limits deal size. Best approached through regional timber industry association relationships for owners of established forest products businesses."
  },
  {
    id: "dayton",
    name: "Dayton",
    county: "Columbia",
    lat: 46.3137,
    lng: -117.9765,
    population: 2695,
    medianHouseholdIncome: 72000,
    populationGrowthPct: 10.1,
    consultingFirmCount: 0,
    smbCount: 22,
    businessMaturityPct: 59,
    ownerAge55PlusPct: 34,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Columbia County seat — a very small market dominated by wheat farming and the growing Walla Walla wine region's eastern edge. Only 1 consulting firm. Wheat farm succession is the primary advisory opportunity — multigenerational family farm businesses often have complex ownership structures and land values that require professional guidance during transition."
  },
  {
    id: "raymond",
    name: "Raymond",
    county: "Pacific",
    lat: 46.6854,
    lng: -123.7334,
    population: 3160,
    medianHouseholdIncome: 53000,
    populationGrowthPct: 2.6,
    consultingFirmCount: 1,
    smbCount: 23,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 31.1,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Pacific County's commercial center with timber, fishing, and rural retail. Very small market ($62k income) with the Pacific County economy showing persistent contraction. Advisory opportunities limited to distressed exits and business closures rather than planned succession."
  },
  {
    id: "stevenson",
    name: "Stevenson",
    county: "Skamania",
    lat: 45.696,
    lng: -121.8892,
    population: 1676,
    medianHouseholdIncome: 78000,
    populationGrowthPct: 12.4,
    consultingFirmCount: 1,
    smbCount: 9,
    businessMaturityPct: 59,
    ownerAge55PlusPct: 36.8,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "Skamania County seat in the Columbia River Gorge — a small community with outdoor recreation, tourism, and government services. Income at $78k is near WA median but the market is too small for standalone practice. The Columbia Gorge recreation economy (windsurfing, kiting, hiking tourism) creates niche hospitality business succession opportunities."
  },
  {
    id: "forks",
    name: "Forks",
    county: "Clallam",
    lat: 47.9497,
    lng: -124.3879,
    population: 3413,
    medianHouseholdIncome: 46000,
    populationGrowthPct: 2.3,
    consultingFirmCount: 1,
    smbCount: 28,
    businessMaturityPct: 60,
    ownerAge55PlusPct: 20.4,
    tier: 5,
    estimated: false,
    dataYear: 2023,
    notes: "A remote Olympic Peninsula community with a timber and tourism (Twilight franchise) economy. Economic challenges make advisory difficult — income at $46k is below the fee capacity floor for standard advisory retainers. Genuine geographic isolation limits competition but also limits deal size. Approach only as an ancillary stop within a comprehensive Olympic Peninsula territory."
  }
];
