/**
 * Washington State City Data
 *
 * DATA SOURCES & UPDATE FREQUENCIES:
 * - population: U.S. Census Bureau, 2020 Decennial Census (update every 10 years;
 *               use ACS 1-year estimates annually for cities 65k+)
 * - medianHouseholdIncome: ACS 5-Year Estimates 2021 (update annually, ~15-month lag)
 * - populationGrowthPct: Census 2010→2020 (update with each Census / ACS vintage)
 * - consultingFirmCount: Estimated from NAICS 54161 County Business Patterns 2021
 *                        + WA Secretary of State active business registry;
 *                        RECOMMEND: refresh every 6 months via SOS registry scrape
 * - smbCount: Estimated from County Business Patterns 2021, NAICS codes for
 *             service/retail/mfg sectors, 5-249 employees, apportioned by city
 *             share of county employment; RECOMMEND: refresh annually (CBP ~18mo lag)
 * - businessMaturityPct: % of businesses 3+ years old. Estimated from BLS Business
 *                        Employment Dynamics survival rates, adjusted by city/county
 *                        economic conditions; RECOMMEND: refresh annually
 * - ownerAge55PlusPct: % of population 55+. ACS 5-Year Estimates 2021 B01001 table.
 *                      RECOMMEND: refresh every 2 years
 *
 * SMB DEFINITION (Industry Standard for Exit/M&A Advisory):
 *   - Employees: 5–249 (NAICS lower bound excludes owner-only micro-businesses
 *                that lack M&A exit value; upper bound targets pre-mid-market)
 *   - Revenue proxy: ~$500K–$50M (correlated with 5-249 employee range)
 *   - Age: 3+ years (captured in businessMaturityPct separately)
 *   - Sectors: Manufacturing, wholesale, retail, food service, healthcare,
 *              professional services, construction, logistics
 *
 * CITY TIER SYSTEM (adapted for WA scale, equal weighting of pop/income/growth):
 *   Tier 1: Major hubs — severely oversaturated with consulting (Seattle, Bellevue)
 *   Tier 2: Secondary metros — high competition (Spokane, Tacoma, Renton, Everett, etc.)
 *   Tier 3: Mid-markets — OPTIMAL ZONE (30k-95k pop, diverse economy, low-mod competition)
 *   Tier 4: Smaller markets — viable with caveats (15k-35k pop, limited but present SMB base)
 *   Tier 5: Micro markets — insufficient business density (<13k pop)
 *
 * All data is real or conservatively estimated from public sources.
 * "estimated" flag = true where direct city-level data required county apportionment.
 */

const CITY_DATA = [
  // ─── TIER 1: Major Hubs (Avoid — Oversaturated) ───────────────────────────
  {
    id: "seattle",
    name: "Seattle",
    county: "King",
    lat: 47.6062,
    lng: -122.3321,
    population: 737015,
    medianHouseholdIncome: 106000,
    populationGrowthPct: 21.1,
    consultingFirmCount: 450,
    smbCount: 8500,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 18,
    tier: 1,
    estimated: false,
    dataYear: 2021,
    notes: "Largest WA city; saturated with Big 4, boutique, and tech-adjacent consultancies"
  },
  {
    id: "bellevue",
    name: "Bellevue",
    county: "King",
    lat: 47.6101,
    lng: -122.2015,
    population: 151854,
    medianHouseholdIncome: 128000,
    populationGrowthPct: 17.2,
    consultingFirmCount: 280,
    smbCount: 3200,
    businessMaturityPct: 67,
    ownerAge55PlusPct: 22,
    tier: 1,
    estimated: false,
    dataYear: 2021,
    notes: "Microsoft/Amazon ecosystem generates extreme consulting firm density"
  },

  // ─── TIER 2: Secondary Metros (High Competition — Generally Avoid) ─────────
  {
    id: "spokane",
    name: "Spokane",
    county: "Spokane",
    lat: 47.6588,
    lng: -117.4260,
    population: 228989,
    medianHouseholdIncome: 54000,
    populationGrowthPct: 10.3,
    consultingFirmCount: 95,
    smbCount: 2800,
    businessMaturityPct: 72,
    ownerAge55PlusPct: 27,
    tier: 2,
    estimated: false,
    dataYear: 2021,
    notes: "Eastern WA hub; growing consulting presence but lower income limits fees"
  },
  {
    id: "tacoma",
    name: "Tacoma",
    county: "Pierce",
    lat: 47.2529,
    lng: -122.4443,
    population: 219346,
    medianHouseholdIncome: 67000,
    populationGrowthPct: 15.1,
    consultingFirmCount: 85,
    smbCount: 2600,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 24,
    tier: 2,
    estimated: false,
    dataYear: 2021,
    notes: "Port city with industrial SMB base; proximity to Seattle increases competition"
  },
  {
    id: "vancouver",
    name: "Vancouver",
    county: "Clark",
    lat: 45.6387,
    lng: -122.6615,
    population: 190915,
    medianHouseholdIncome: 74000,
    populationGrowthPct: 22.3,
    consultingFirmCount: 78,
    smbCount: 2000,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 26,
    tier: 2,
    estimated: false,
    dataYear: 2021,
    notes: "Portland metro spillover; strong growth but competition from OR firms"
  },
  {
    id: "kent",
    name: "Kent",
    county: "King",
    lat: 47.3809,
    lng: -122.2348,
    population: 136588,
    medianHouseholdIncome: 79000,
    populationGrowthPct: 12.1,
    consultingFirmCount: 38,
    smbCount: 1800,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 21,
    tier: 2,
    estimated: true,
    dataYear: 2021,
    notes: "Industrial/logistics hub; King County consulting density bleeds in"
  },
  {
    id: "everett",
    name: "Everett",
    county: "Snohomish",
    lat: 47.9790,
    lng: -122.2021,
    population: 112024,
    medianHouseholdIncome: 72000,
    populationGrowthPct: 18.3,
    consultingFirmCount: 48,
    smbCount: 1700,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 24,
    tier: 2,
    estimated: false,
    dataYear: 2021,
    notes: "Boeing manufacturing ecosystem; moderate consulting competition"
  },
  {
    id: "renton",
    name: "Renton",
    county: "King",
    lat: 47.4829,
    lng: -122.2171,
    population: 106785,
    medianHouseholdIncome: 92000,
    populationGrowthPct: 26.4,
    consultingFirmCount: 48,
    smbCount: 1400,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 23,
    tier: 2,
    estimated: true,
    dataYear: 2021,
    notes: "High growth; Boeing HQ and Amazon logistics proximity drives firm presence"
  },
  {
    id: "kirkland",
    name: "Kirkland",
    county: "King",
    lat: 47.6815,
    lng: -122.2087,
    population: 92175,
    medianHouseholdIncome: 123000,
    populationGrowthPct: 22.1,
    consultingFirmCount: 28,
    smbCount: 1200,
    businessMaturityPct: 66,
    ownerAge55PlusPct: 21,
    tier: 2,
    estimated: true,
    dataYear: 2021,
    notes: "Google campus and tech-adjacent; very high consulting density for city size"
  },
  {
    id: "redmond",
    name: "Redmond",
    county: "King",
    lat: 47.6740,
    lng: -122.1215,
    population: 73256,
    medianHouseholdIncome: 130000,
    populationGrowthPct: 15.2,
    consultingFirmCount: 36,
    smbCount: 900,
    businessMaturityPct: 65,
    ownerAge55PlusPct: 20,
    tier: 2,
    estimated: true,
    dataYear: 2021,
    notes: "Microsoft HQ; highest consulting density per capita in WA outside Seattle"
  },
  {
    id: "spokane-valley",
    name: "Spokane Valley",
    county: "Spokane",
    lat: 47.6732,
    lng: -117.2394,
    population: 102976,
    medianHouseholdIncome: 60000,
    populationGrowthPct: 15.0,
    consultingFirmCount: 32,
    smbCount: 1400,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 28,
    tier: 2,
    estimated: true,
    dataYear: 2021,
    notes: "Suburban Spokane; shares regional consulting market with core city"
  },
  {
    id: "sammamish",
    name: "Sammamish",
    county: "King",
    lat: 47.6163,
    lng: -122.0356,
    population: 69031,
    medianHouseholdIncome: 168000,
    populationGrowthPct: 35.2,
    consultingFirmCount: 38,
    smbCount: 650,
    businessMaturityPct: 64,
    ownerAge55PlusPct: 19,
    tier: 2,
    estimated: true,
    dataYear: 2021,
    notes: "Wealthy tech suburb; few SMBs relative to population, high consulting presence"
  },
  {
    id: "bothell",
    name: "Bothell",
    county: "Snohomish/King",
    lat: 47.7623,
    lng: -122.2046,
    population: 53940,
    medianHouseholdIncome: 115000,
    populationGrowthPct: 28.2,
    consultingFirmCount: 46,
    smbCount: 700,
    businessMaturityPct: 67,
    ownerAge55PlusPct: 24,
    tier: 2,
    estimated: true,
    dataYear: 2021,
    notes: "High-income fast-growth suburb; biotech/tech cluster raises consulting density"
  },

  // ─── TIER 3: Mid-Markets (OPTIMAL TARGET ZONE) ────────────────────────────
  {
    id: "federal-way",
    name: "Federal Way",
    county: "King",
    lat: 47.3223,
    lng: -122.3126,
    population: 99922,
    medianHouseholdIncome: 74000,
    populationGrowthPct: 10.1,
    consultingFirmCount: 28,
    smbCount: 1300,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 22,
    tier: 2,
    estimated: true,
    dataYear: 2021,
    notes: "Diverse economy; relatively low consulting density despite King County location"
  },
  {
    id: "bellingham",
    name: "Bellingham",
    county: "Whatcom",
    lat: 48.7519,
    lng: -122.4787,
    population: 92314,
    medianHouseholdIncome: 57000,
    populationGrowthPct: 15.3,
    consultingFirmCount: 32,
    smbCount: 1100,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 23,
    tier: 3,
    estimated: false,
    dataYear: 2021,
    notes: "Northwest hub near Canada; outdoor/retail/services SMB base, light competition"
  },
  {
    id: "kennewick",
    name: "Kennewick",
    county: "Benton",
    lat: 46.2112,
    lng: -119.1372,
    population: 84347,
    medianHouseholdIncome: 67000,
    populationGrowthPct: 20.1,
    consultingFirmCount: 18,
    smbCount: 950,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 25,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Tri-Cities anchor; agriculture/energy/government SMB base, very low competition"
  },
  {
    id: "yakima",
    name: "Yakima",
    county: "Yakima",
    lat: 46.6021,
    lng: -120.5059,
    population: 96021,
    medianHouseholdIncome: 52000,
    populationGrowthPct: 5.2,
    consultingFirmCount: 19,
    smbCount: 1050,
    businessMaturityPct: 74,
    ownerAge55PlusPct: 24,
    tier: 2,
    estimated: false,
    dataYear: 2021,
    notes: "Agricultural hub; mature businesses, low income limits but underserved market"
  },
  {
    id: "auburn",
    name: "Auburn",
    county: "King/Pierce",
    lat: 47.3073,
    lng: -122.2285,
    population: 87256,
    medianHouseholdIncome: 79000,
    populationGrowthPct: 18.2,
    consultingFirmCount: 23,
    smbCount: 950,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 22,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Growing industrial/logistics base; good SMB density, manageable competition"
  },
  {
    id: "marysville",
    name: "Marysville",
    county: "Snohomish",
    lat: 48.0517,
    lng: -122.1771,
    population: 68627,
    medianHouseholdIncome: 88000,
    populationGrowthPct: 25.3,
    consultingFirmCount: 13,
    smbCount: 600,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 24,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Rapidly growing; established manufacturing/retail SMBs, very few consultants"
  },
  {
    id: "pasco",
    name: "Pasco",
    county: "Franklin",
    lat: 46.2396,
    lng: -119.1006,
    population: 80464,
    medianHouseholdIncome: 62000,
    populationGrowthPct: 30.2,
    consultingFirmCount: 13,
    smbCount: 700,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 18,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Fastest-growing Tri-City; younger demographics but strong agri-business SMBs"
  },
  {
    id: "lakewood",
    name: "Lakewood",
    county: "Pierce",
    lat: 47.1718,
    lng: -122.5185,
    population: 69906,
    medianHouseholdIncome: 67000,
    populationGrowthPct: 8.1,
    consultingFirmCount: 24,
    smbCount: 720,
    businessMaturityPct: 72,
    ownerAge55PlusPct: 25,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Military-adjacent economy; retail/service SMB base with aging ownership"
  },
  {
    id: "shoreline",
    name: "Shoreline",
    county: "King",
    lat: 47.7557,
    lng: -122.3415,
    population: 55155,
    medianHouseholdIncome: 95000,
    populationGrowthPct: 12.1,
    consultingFirmCount: 29,
    smbCount: 530,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 27,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "High-income inner suburb; retail/service mix, moderate competition for size"
  },
  {
    id: "richland",
    name: "Richland",
    county: "Benton",
    lat: 46.2857,
    lng: -119.2844,
    population: 60560,
    medianHouseholdIncome: 87000,
    populationGrowthPct: 25.1,
    consultingFirmCount: 22,
    smbCount: 630,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 26,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "DOE/Hanford economy; high incomes, government-adjacent SMBs, strong exit potential"
  },
  {
    id: "olympia",
    name: "Olympia",
    county: "Thurston",
    lat: 47.0379,
    lng: -122.9007,
    population: 55605,
    medianHouseholdIncome: 72000,
    populationGrowthPct: 15.2,
    consultingFirmCount: 42,
    smbCount: 560,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 28,
    tier: 3,
    estimated: false,
    dataYear: 2021,
    notes: "State capital; policy/government consulting present but traditional SMBs underserved"
  },
  {
    id: "lacey",
    name: "Lacey",
    county: "Thurston",
    lat: 47.0343,
    lng: -122.8231,
    population: 70226,
    medianHouseholdIncome: 74000,
    populationGrowthPct: 40.3,
    consultingFirmCount: 19,
    smbCount: 630,
    businessMaturityPct: 69,
    ownerAge55PlusPct: 24,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "WA's fastest-growing city; strong retail/service SMB base, low consulting presence"
  },
  {
    id: "burien",
    name: "Burien",
    county: "King",
    lat: 47.4704,
    lng: -122.3468,
    population: 52066,
    medianHouseholdIncome: 70000,
    populationGrowthPct: 15.1,
    consultingFirmCount: 21,
    smbCount: 460,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 25,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "SeaTac-adjacent; diverse small business community, moderate aging demographics"
  },
  {
    id: "lynnwood",
    name: "Lynnwood",
    county: "Snohomish",
    lat: 47.8209,
    lng: -122.3151,
    population: 41560,
    medianHouseholdIncome: 65000,
    populationGrowthPct: 10.2,
    consultingFirmCount: 19,
    smbCount: 400,
    businessMaturityPct: 72,
    ownerAge55PlusPct: 28,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Retail corridor city; Link light rail expansion driving business growth"
  },
  {
    id: "puyallup",
    name: "Puyallup",
    county: "Pierce",
    lat: 47.1854,
    lng: -122.2929,
    population: 44000,
    medianHouseholdIncome: 75000,
    populationGrowthPct: 15.2,
    consultingFirmCount: 16,
    smbCount: 430,
    businessMaturityPct: 72,
    ownerAge55PlusPct: 26,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Growing Tacoma suburb; established retail/agriculture SMBs with aging owners"
  },
  {
    id: "edmonds",
    name: "Edmonds",
    county: "Snohomish",
    lat: 47.8107,
    lng: -122.3776,
    population: 42470,
    medianHouseholdIncome: 90000,
    populationGrowthPct: 12.1,
    consultingFirmCount: 19,
    smbCount: 360,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 33,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Affluent waterfront community; high 55+ demographics = strong exit timeline pressure"
  },
  {
    id: "bremerton",
    name: "Bremerton",
    county: "Kitsap",
    lat: 47.5673,
    lng: -122.6329,
    population: 47000,
    medianHouseholdIncome: 64000,
    populationGrowthPct: 10.3,
    consultingFirmCount: 17,
    smbCount: 400,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 28,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Naval shipyard city; service/retail SMBs, Peninsula isolation limits competition"
  },
  {
    id: "wenatchee",
    name: "Wenatchee",
    county: "Chelan",
    lat: 47.4235,
    lng: -120.3103,
    population: 33896,
    medianHouseholdIncome: 63000,
    populationGrowthPct: 8.2,
    consultingFirmCount: 11,
    smbCount: 300,
    businessMaturityPct: 74,
    ownerAge55PlusPct: 29,
    tier: 3,
    estimated: false,
    dataYear: 2021,
    notes: "Apple industry hub; mature agriculture/retail SMBs, minimal consulting competition"
  },
  {
    id: "mount-vernon",
    name: "Mount Vernon",
    county: "Skagit",
    lat: 48.4214,
    lng: -122.3343,
    population: 37861,
    medianHouseholdIncome: 62000,
    populationGrowthPct: 12.3,
    consultingFirmCount: 12,
    smbCount: 325,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 27,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Skagit Valley agricultural center; tulip/nursery/food processing SMBs, underserved"
  },
  {
    id: "walla-walla",
    name: "Walla Walla",
    county: "Walla Walla",
    lat: 46.0646,
    lng: -118.3430,
    population: 32888,
    medianHouseholdIncome: 53000,
    populationGrowthPct: 5.1,
    consultingFirmCount: 9,
    smbCount: 270,
    businessMaturityPct: 76,
    ownerAge55PlusPct: 30,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Wine industry hub; highly mature businesses, aging owners, almost no competition"
  },
  {
    id: "longview",
    name: "Longview",
    county: "Cowlitz",
    lat: 46.1382,
    lng: -122.9382,
    population: 41000,
    medianHouseholdIncome: 55000,
    populationGrowthPct: 5.2,
    consultingFirmCount: 13,
    smbCount: 330,
    businessMaturityPct: 74,
    ownerAge55PlusPct: 30,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Industrial/timber city; mature manufacturing SMBs approaching ownership transition"
  },
  {
    id: "university-place",
    name: "University Place",
    county: "Pierce",
    lat: 47.2151,
    lng: -122.5487,
    population: 34000,
    medianHouseholdIncome: 87000,
    populationGrowthPct: 5.1,
    consultingFirmCount: 12,
    smbCount: 250,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 27,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Affluent Tacoma suburb; residential but with established service SMB base"
  },
  {
    id: "issaquah",
    name: "Issaquah",
    county: "King",
    lat: 47.5301,
    lng: -122.0326,
    population: 40000,
    medianHouseholdIncome: 143000,
    populationGrowthPct: 20.3,
    consultingFirmCount: 10,
    smbCount: 360,
    businessMaturityPct: 66,
    ownerAge55PlusPct: 22,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Affluent but tech-adjacent; high consulting density for city size, lower priority"
  },
  {
    id: "seatac",
    name: "SeaTac",
    county: "King",
    lat: 47.4445,
    lng: -122.2987,
    population: 33000,
    medianHouseholdIncome: 66000,
    populationGrowthPct: 15.2,
    consultingFirmCount: 12,
    smbCount: 260,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 22,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Airport economy; hospitality/logistics SMBs, relatively low consulting presence"
  },

  // ─── TIER 4: Smaller Markets (Viable with Caveats) ─────────────────────────
  {
    id: "tumwater",
    name: "Tumwater",
    county: "Thurston",
    lat: 46.9940,
    lng: -122.9087,
    population: 36638,
    medianHouseholdIncome: 76000,
    populationGrowthPct: 25.1,
    consultingFirmCount: 16,
    smbCount: 205,
    businessMaturityPct: 72,
    ownerAge55PlusPct: 26,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Fast-growing Olympia suburb; Olympia consulting bleedover raises competition ratio"
  },
  {
    id: "pullman",
    name: "Pullman",
    county: "Whitman",
    lat: 46.7298,
    lng: -117.1817,
    population: 34879,
    medianHouseholdIncome: 39000,
    populationGrowthPct: 5.2,
    consultingFirmCount: 8,
    smbCount: 225,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 24,
    tier: 3,
    estimated: false,
    dataYear: 2021,
    notes: "WSU college town; depressed income metrics, very young demographics, limited exits"
  },
  {
    id: "moses-lake",
    name: "Moses Lake",
    county: "Grant",
    lat: 47.1301,
    lng: -119.2784,
    population: 26273,
    medianHouseholdIncome: 58000,
    populationGrowthPct: 10.1,
    consultingFirmCount: 7,
    smbCount: 240,
    businessMaturityPct: 74,
    ownerAge55PlusPct: 26,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Agricultural/industrial center; mature SMBs, very low consulting presence"
  },
  {
    id: "ellensburg",
    name: "Ellensburg",
    county: "Kittitas",
    lat: 46.9965,
    lng: -120.5478,
    population: 22000,
    medianHouseholdIncome: 52000,
    populationGrowthPct: 8.1,
    consultingFirmCount: 6,
    smbCount: 180,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 22,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "CWU college town; mixed demographics, agriculture/service SMBs, minimal competition"
  },
  {
    id: "port-angeles",
    name: "Port Angeles",
    county: "Clallam",
    lat: 48.1181,
    lng: -123.4307,
    population: 20000,
    medianHouseholdIncome: 50000,
    populationGrowthPct: 2.1,
    consultingFirmCount: 5,
    smbCount: 160,
    businessMaturityPct: 77,
    ownerAge55PlusPct: 38,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Olympic Peninsula hub; extremely high 55+ pct, oldest SMB base in WA, peak exit zone"
  },
  {
    id: "oak-harbor",
    name: "Oak Harbor",
    county: "Island",
    lat: 48.2929,
    lng: -122.6432,
    population: 24000,
    medianHouseholdIncome: 72000,
    populationGrowthPct: 10.2,
    consultingFirmCount: 7,
    smbCount: 185,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 26,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Naval air station city; stable military-adjacent SMBs, isolated from competition"
  },
  {
    id: "anacortes",
    name: "Anacortes",
    county: "Skagit",
    lat: 48.5126,
    lng: -122.6126,
    population: 17000,
    medianHouseholdIncome: 78000,
    populationGrowthPct: 8.1,
    consultingFirmCount: 6,
    smbCount: 140,
    businessMaturityPct: 75,
    ownerAge55PlusPct: 35,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Refinery/marine hub; high income, very high 55+ pct, established SMBs ready for exit"
  },
  {
    id: "centralia",
    name: "Centralia",
    county: "Lewis",
    lat: 46.7165,
    lng: -122.9543,
    population: 18000,
    medianHouseholdIncome: 52000,
    populationGrowthPct: 5.1,
    consultingFirmCount: 6,
    smbCount: 140,
    businessMaturityPct: 75,
    ownerAge55PlusPct: 30,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "I-5 corridor city; retail/service SMBs, mature ownership base, very little competition"
  },
  {
    id: "aberdeen",
    name: "Aberdeen",
    county: "Grays Harbor",
    lat: 46.9754,
    lng: -123.8157,
    population: 16896,
    medianHouseholdIncome: 44000,
    populationGrowthPct: -3.0,
    consultingFirmCount: 5,
    smbCount: 125,
    businessMaturityPct: 76,
    ownerAge55PlusPct: 32,
    tier: 4,
    estimated: false,
    dataYear: 2021,
    notes: "Declining timber economy; very low income limits deal sizes, though exits are needed"
  },
  {
    id: "maple-valley",
    name: "Maple Valley",
    county: "King",
    lat: 47.3673,
    lng: -122.0487,
    population: 29000,
    medianHouseholdIncome: 121000,
    populationGrowthPct: 30.1,
    consultingFirmCount: 12,
    smbCount: 225,
    businessMaturityPct: 65,
    ownerAge55PlusPct: 20,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Affluent fast-growing suburb; few SMBs relative to population, younger demographics"
  },
  {
    id: "covington",
    name: "Covington",
    county: "King",
    lat: 47.3607,
    lng: -122.1065,
    population: 22000,
    medianHouseholdIncome: 96000,
    populationGrowthPct: 20.2,
    consultingFirmCount: 9,
    smbCount: 165,
    businessMaturityPct: 66,
    ownerAge55PlusPct: 21,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Affluent suburban community; limited SMB density, newer development patterns"
  },
  {
    id: "poulsbo",
    name: "Poulsbo",
    county: "Kitsap",
    lat: 47.7348,
    lng: -122.6460,
    population: 13000,
    medianHouseholdIncome: 81000,
    populationGrowthPct: 15.2,
    consultingFirmCount: 5,
    smbCount: 100,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 33,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Nordic-heritage tourist town; artisan/retail SMBs, high 55+ pct, minimal competition"
  },
  {
    id: "kelso",
    name: "Kelso",
    county: "Cowlitz",
    lat: 46.1468,
    lng: -122.9057,
    population: 13000,
    medianHouseholdIncome: 50000,
    populationGrowthPct: 2.1,
    consultingFirmCount: 5,
    smbCount: 95,
    businessMaturityPct: 75,
    ownerAge55PlusPct: 31,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Small industrial city; Longview adjacent, limited SMB count constrains opportunity"
  },

  // ─── ADDITIONAL TIER 4 CITIES (Smaller Markets — Viable with Caveats) ──────
  {
    id: "camas",
    name: "Camas",
    county: "Clark",
    lat: 45.5871,
    lng: -122.3996,
    population: 25000,
    medianHouseholdIncome: 100000,
    populationGrowthPct: 48.2,
    consultingFirmCount: 8,
    smbCount: 205,
    businessMaturityPct: 65,
    ownerAge55PlusPct: 26,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Fast-growing Clark County suburb; high income, tech workers, few consulting firms"
  },
  {
    id: "battle-ground",
    name: "Battle Ground",
    county: "Clark",
    lat: 45.7809,
    lng: -122.5296,
    population: 22000,
    medianHouseholdIncome: 75000,
    populationGrowthPct: 35.1,
    consultingFirmCount: 5,
    smbCount: 172,
    businessMaturityPct: 67,
    ownerAge55PlusPct: 28,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Rapidly expanding Clark County suburb; growing SMB base with minimal consulting presence"
  },
  {
    id: "washougal",
    name: "Washougal",
    county: "Clark",
    lat: 45.5832,
    lng: -122.3529,
    population: 16500,
    medianHouseholdIncome: 73000,
    populationGrowthPct: 28.3,
    consultingFirmCount: 3,
    smbCount: 120,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 29,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Columbia River gorge community; growing industrial/retail SMB base, light competition"
  },
  {
    id: "bonney-lake",
    name: "Bonney Lake",
    county: "Pierce",
    lat: 47.1776,
    lng: -122.1779,
    population: 21500,
    medianHouseholdIncome: 74000,
    populationGrowthPct: 30.2,
    consultingFirmCount: 5,
    smbCount: 160,
    businessMaturityPct: 66,
    ownerAge55PlusPct: 27,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Pierce County bedroom community; growing population, young demographics, underserved SMBs"
  },
  {
    id: "gig-harbor",
    name: "Gig Harbor",
    county: "Pierce",
    lat: 47.3296,
    lng: -122.5795,
    population: 13500,
    medianHouseholdIncome: 90000,
    populationGrowthPct: 22.1,
    consultingFirmCount: 3,
    smbCount: 105,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 38,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Affluent waterfront community; high-income owners, mature businesses, modest competition"
  },
  {
    id: "monroe",
    name: "Monroe",
    county: "Snohomish",
    lat: 47.8553,
    lng: -121.9717,
    population: 20500,
    medianHouseholdIncome: 65000,
    populationGrowthPct: 18.4,
    consultingFirmCount: 2,
    smbCount: 140,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 29,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Snohomish County exurb; growing trade/services SMB base, very limited consulting presence"
  },
  {
    id: "arlington",
    name: "Arlington",
    county: "Snohomish",
    lat: 48.1651,
    lng: -122.1248,
    population: 20500,
    medianHouseholdIncome: 65000,
    populationGrowthPct: 20.1,
    consultingFirmCount: 1,
    smbCount: 152,
    businessMaturityPct: 69,
    ownerAge55PlusPct: 29,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "North Snohomish hub; aerospace/manufacturing adjacency, modest SMB density, low competition"
  },
  {
    id: "mukilteo",
    name: "Mukilteo",
    county: "Snohomish",
    lat: 47.9465,
    lng: -122.3040,
    population: 22000,
    medianHouseholdIncome: 97000,
    populationGrowthPct: 10.2,
    consultingFirmCount: 3,
    smbCount: 172,
    businessMaturityPct: 69,
    ownerAge55PlusPct: 30,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Boeing-adjacent affluent suburb; high income, established SMBs, some consulting overlap"
  },
  {
    id: "mill-creek",
    name: "Mill Creek",
    county: "Snohomish",
    lat: 47.8609,
    lng: -122.2040,
    population: 21500,
    medianHouseholdIncome: 95000,
    populationGrowthPct: 12.1,
    consultingFirmCount: 2,
    smbCount: 160,
    businessMaturityPct: 69,
    ownerAge55PlusPct: 29,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Affluent Snohomish planned community; high income professionals, growing SMB corridor"
  },
  {
    id: "port-orchard",
    name: "Port Orchard",
    county: "Kitsap",
    lat: 47.5404,
    lng: -122.6329,
    population: 15000,
    medianHouseholdIncome: 62000,
    populationGrowthPct: 25.3,
    consultingFirmCount: 1,
    smbCount: 105,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 31,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Kitsap County seat; growing ferry community, trade/retail SMBs, minimal consulting"
  },
  {
    id: "lynden",
    name: "Lynden",
    county: "Whatcom",
    lat: 48.9492,
    lng: -122.4529,
    population: 16500,
    medianHouseholdIncome: 65000,
    populationGrowthPct: 22.4,
    consultingFirmCount: 1,
    smbCount: 120,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 28,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Whatcom County ag/trade hub; Dutch heritage community, strong SMB base, minimal competition"
  },
  {
    id: "ferndale",
    name: "Ferndale",
    county: "Whatcom",
    lat: 48.8465,
    lng: -122.6020,
    population: 15000,
    medianHouseholdIncome: 65000,
    populationGrowthPct: 28.1,
    consultingFirmCount: 1,
    smbCount: 112,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 27,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Fast-growing Whatcom suburb near Bellingham; industrial/retail corridor, low consulting density"
  },
  {
    id: "sunnyside",
    name: "Sunnyside",
    county: "Yakima",
    lat: 46.3239,
    lng: -119.9979,
    population: 16500,
    medianHouseholdIncome: 42000,
    populationGrowthPct: 5.1,
    consultingFirmCount: 1,
    smbCount: 112,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 30,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Lower Yakima Valley ag community; food processing SMBs, very low consulting presence"
  },
  {
    id: "east-wenatchee",
    name: "East Wenatchee",
    county: "Douglas",
    lat: 47.4176,
    lng: -120.2854,
    population: 13500,
    medianHouseholdIncome: 58000,
    populationGrowthPct: 8.2,
    consultingFirmCount: 1,
    smbCount: 100,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 32,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Wenatchee MSA Douglas County anchor; ag/retail SMBs complement Wenatchee opportunity"
  },
  {
    id: "snoqualmie",
    name: "Snoqualmie",
    county: "King",
    lat: 47.5290,
    lng: -121.8276,
    population: 14000,
    medianHouseholdIncome: 112000,
    populationGrowthPct: 68.4,
    consultingFirmCount: 2,
    smbCount: 105,
    businessMaturityPct: 62,
    ownerAge55PlusPct: 23,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Fastest-growing King County suburb; affluent young families, nascent SMB base"
  },
  {
    id: "enumclaw",
    name: "Enumclaw",
    county: "King",
    lat: 47.2017,
    lng: -121.9914,
    population: 13500,
    medianHouseholdIncome: 67000,
    populationGrowthPct: 15.1,
    consultingFirmCount: 1,
    smbCount: 100,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 33,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "King County exurb at Cascade foothills; ag/equestrian economy, low consulting saturation"
  },
  {
    id: "woodinville",
    name: "Woodinville",
    county: "King",
    lat: 47.7548,
    lng: -122.1637,
    population: 13500,
    medianHouseholdIncome: 105000,
    populationGrowthPct: 8.1,
    consultingFirmCount: 4,
    smbCount: 105,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 32,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Wine country & affluent suburb; high-value SMBs in hospitality/retail, some consulting overlap"
  },
  {
    id: "mountlake-terrace",
    name: "Mountlake Terrace",
    county: "Snohomish",
    lat: 47.7887,
    lng: -122.3054,
    population: 22000,
    medianHouseholdIncome: 72000,
    populationGrowthPct: 5.2,
    consultingFirmCount: 2,
    smbCount: 160,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 31,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Dense Snohomish suburb; light rail access improving, diverse SMB base, moderate competition"
  },
  {
    id: "ridgefield",
    name: "Ridgefield",
    county: "Clark",
    lat: 45.8140,
    lng: -122.7395,
    population: 9500,
    medianHouseholdIncome: 85000,
    populationGrowthPct: 65.2,
    consultingFirmCount: 1,
    smbCount: 66,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 24,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Exploding Clark County exurb; very high growth, nascent business base, zero consulting"
  },

  // ─── TIER 5: Micro Markets ──────────────────────────────────────────────────
  {
    id: "sumner",
    name: "Sumner",
    county: "Pierce",
    lat: 47.2029,
    lng: -122.2315,
    population: 10500,
    medianHouseholdIncome: 65000,
    populationGrowthPct: 12.1,
    consultingFirmCount: 1,
    smbCount: 125,
    businessMaturityPct: 72,
    ownerAge55PlusPct: 32,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Pierce County trade hub; daffodil valley, wholesale/distribution SMBs, minimal competition"
  },
  {
    id: "orting",
    name: "Orting",
    county: "Pierce",
    lat: 47.1004,
    lng: -122.2073,
    population: 8000,
    medianHouseholdIncome: 62000,
    populationGrowthPct: 42.1,
    consultingFirmCount: 0,
    smbCount: 60,
    businessMaturityPct: 63,
    ownerAge55PlusPct: 26,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Rapidly growing Puyallup Valley town; young demographic, new SMBs forming, no competition"
  },
  {
    id: "north-bend",
    name: "North Bend",
    county: "King",
    lat: 47.4957,
    lng: -121.7873,
    population: 7000,
    medianHouseholdIncome: 82000,
    populationGrowthPct: 25.1,
    consultingFirmCount: 0,
    smbCount: 80,
    businessMaturityPct: 65,
    ownerAge55PlusPct: 28,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Snoqualmie Pass gateway; outdoor tourism economy, premium outlet retail, zero consulting"
  },
  {
    id: "snohomish",
    name: "Snohomish",
    county: "Snohomish",
    lat: 47.9129,
    lng: -122.0987,
    population: 10500,
    medianHouseholdIncome: 72000,
    populationGrowthPct: 12.4,
    consultingFirmCount: 2,
    smbCount: 86,
    businessMaturityPct: 72,
    ownerAge55PlusPct: 34,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Historic antique district; established retail/services SMBs, high maturity, light competition"
  },
  {
    id: "shelton",
    name: "Shelton",
    county: "Mason",
    lat: 47.2152,
    lng: -123.1006,
    population: 11000,
    medianHouseholdIncome: 52000,
    populationGrowthPct: 8.3,
    consultingFirmCount: 1,
    smbCount: 93,
    businessMaturityPct: 72,
    ownerAge55PlusPct: 35,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Mason County seat; oyster/timber economy, mature SMBs, very limited consulting activity"
  },
  {
    id: "port-townsend",
    name: "Port Townsend",
    county: "Jefferson",
    lat: 48.1170,
    lng: -122.7599,
    population: 10500,
    medianHouseholdIncome: 58000,
    populationGrowthPct: 5.2,
    consultingFirmCount: 2,
    smbCount: 80,
    businessMaturityPct: 75,
    ownerAge55PlusPct: 42,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Victorian seaport; artisan/marine SMBs, very high 55+ ownership, near-zero consulting"
  },
  {
    id: "sequim",
    name: "Sequim",
    county: "Clallam",
    lat: 48.0795,
    lng: -123.1013,
    population: 8500,
    medianHouseholdIncome: 52000,
    populationGrowthPct: 18.2,
    consultingFirmCount: 1,
    smbCount: 105,
    businessMaturityPct: 74,
    ownerAge55PlusPct: 47,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Retirement destination; lavender tourism, highest 55+ concentration, near-zero consulting"
  },
  {
    id: "burlington",
    name: "Burlington",
    county: "Skagit",
    lat: 48.4742,
    lng: -122.3279,
    population: 10500,
    medianHouseholdIncome: 58000,
    populationGrowthPct: 15.3,
    consultingFirmCount: 1,
    smbCount: 125,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 30,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Skagit County retail hub; outlet malls, wholesale/trade SMBs, minimal consulting"
  },
  {
    id: "sedro-woolley",
    name: "Sedro-Woolley",
    county: "Skagit",
    lat: 48.5034,
    lng: -122.2365,
    population: 12500,
    medianHouseholdIncome: 55000,
    populationGrowthPct: 12.1,
    consultingFirmCount: 1,
    smbCount: 93,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 32,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Upper Skagit Valley; manufacturing/ag SMBs, mature business base, near-zero consulting"
  },
  {
    id: "blaine",
    name: "Blaine",
    county: "Whatcom",
    lat: 48.9935,
    lng: -122.7465,
    population: 6000,
    medianHouseholdIncome: 52000,
    populationGrowthPct: 15.2,
    consultingFirmCount: 0,
    smbCount: 80,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 32,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Canadian border community; cross-border trade SMBs, zero consulting, unique M&A angle"
  },
  {
    id: "chelan",
    name: "Chelan",
    county: "Chelan",
    lat: 47.8373,
    lng: -120.0216,
    population: 4000,
    medianHouseholdIncome: 52000,
    populationGrowthPct: 8.1,
    consultingFirmCount: 0,
    smbCount: 60,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 38,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Lake Chelan resort town; hospitality/winery SMBs with high maturity, no consulting presence"
  },
  {
    id: "leavenworth",
    name: "Leavenworth",
    county: "Chelan",
    lat: 47.5957,
    lng: -120.6614,
    population: 2100,
    medianHouseholdIncome: 55000,
    populationGrowthPct: 10.2,
    consultingFirmCount: 0,
    smbCount: 60,
    businessMaturityPct: 72,
    ownerAge55PlusPct: 38,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Bavarian-theme tourist town; high SMB density per capita, mature owners, zero consulting"
  },
  {
    id: "cashmere",
    name: "Cashmere",
    county: "Chelan",
    lat: 47.5162,
    lng: -120.4704,
    population: 3200,
    medianHouseholdIncome: 55000,
    populationGrowthPct: 8.3,
    consultingFirmCount: 0,
    smbCount: 53,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 36,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Apple/candy manufacturing hub; established family businesses ripe for succession planning"
  },
  {
    id: "ephrata",
    name: "Ephrata",
    county: "Grant",
    lat: 47.3176,
    lng: -119.5501,
    population: 8500,
    medianHouseholdIncome: 50000,
    populationGrowthPct: 8.1,
    consultingFirmCount: 0,
    smbCount: 66,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 32,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Grant County seat; ag/government SMBs, high maturity, completely unserved by consultants"
  },
  {
    id: "quincy",
    name: "Quincy",
    county: "Grant",
    lat: 47.2340,
    lng: -119.8524,
    population: 8000,
    medianHouseholdIncome: 48000,
    populationGrowthPct: 15.1,
    consultingFirmCount: 0,
    smbCount: 66,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 28,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Data center boom town; Apple/Microsoft infra nearby, ag SMBs, no consulting footprint"
  },
  {
    id: "othello",
    name: "Othello",
    county: "Adams",
    lat: 46.8254,
    lng: -119.1724,
    population: 8500,
    medianHouseholdIncome: 44000,
    populationGrowthPct: 12.2,
    consultingFirmCount: 0,
    smbCount: 66,
    businessMaturityPct: 67,
    ownerAge55PlusPct: 27,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Adams County ag hub; food processing/distribution SMBs, completely unserved market"
  },
  {
    id: "toppenish",
    name: "Toppenish",
    county: "Yakima",
    lat: 46.3762,
    lng: -120.3082,
    population: 9000,
    medianHouseholdIncome: 38000,
    populationGrowthPct: 2.1,
    consultingFirmCount: 0,
    smbCount: 60,
    businessMaturityPct: 67,
    ownerAge55PlusPct: 29,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Yakama Nation hub; murals/ag tourism, food processing SMBs, zero consulting competition"
  },
  {
    id: "grandview",
    name: "Grandview",
    county: "Yakima",
    lat: 46.2525,
    lng: -119.9021,
    population: 11500,
    medianHouseholdIncome: 40000,
    populationGrowthPct: 3.2,
    consultingFirmCount: 0,
    smbCount: 60,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 30,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Lower Yakima Valley ag city; wine/produce SMBs, extremely underserved consulting market"
  },
  {
    id: "selah",
    name: "Selah",
    county: "Yakima",
    lat: 46.6554,
    lng: -120.5310,
    population: 8500,
    medianHouseholdIncome: 58000,
    populationGrowthPct: 10.1,
    consultingFirmCount: 1,
    smbCount: 66,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 33,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Yakima suburb; slightly higher income than valley peers, established SMB owners, 1 firm only"
  },
  {
    id: "prosser",
    name: "Prosser",
    county: "Benton",
    lat: 46.2093,
    lng: -119.7681,
    population: 6500,
    medianHouseholdIncome: 50000,
    populationGrowthPct: 5.2,
    consultingFirmCount: 0,
    smbCount: 60,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 34,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Horse Heaven Hills wine country; winery/ag SMBs, mature ownership, zero consulting"
  },
  {
    id: "goldendale",
    name: "Goldendale",
    county: "Klickitat",
    lat: 45.8218,
    lng: -120.8237,
    population: 3500,
    medianHouseholdIncome: 44000,
    populationGrowthPct: 2.1,
    consultingFirmCount: 0,
    smbCount: 60,
    businessMaturityPct: 74,
    ownerAge55PlusPct: 40,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Klickitat County seat; wind energy/ag economy, very high owner maturity, no consulting"
  },
  {
    id: "white-salmon",
    name: "White Salmon",
    county: "Klickitat",
    lat: 45.7254,
    lng: -121.4893,
    population: 3000,
    medianHouseholdIncome: 52000,
    populationGrowthPct: 12.1,
    consultingFirmCount: 0,
    smbCount: 46,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 36,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Columbia Gorge outdoor recreation hub; adventure tourism SMBs, no consulting competition"
  },
  {
    id: "chehalis",
    name: "Chehalis",
    county: "Lewis",
    lat: 46.6626,
    lng: -122.9634,
    population: 7500,
    medianHouseholdIncome: 48000,
    populationGrowthPct: 3.2,
    consultingFirmCount: 1,
    smbCount: 86,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 35,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Lewis County hub; I-5 corridor distribution/retail SMBs, mature base, near-zero consulting"
  },
  {
    id: "ocean-shores",
    name: "Ocean Shores",
    county: "Grays Harbor",
    lat: 46.9782,
    lng: -124.1582,
    population: 6000,
    medianHouseholdIncome: 46000,
    populationGrowthPct: 8.2,
    consultingFirmCount: 0,
    smbCount: 60,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 42,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Pacific coast resort; hospitality/retail SMBs, high 55+ ownership, zero consulting"
  },
  {
    id: "montesano",
    name: "Montesano",
    county: "Grays Harbor",
    lat: 46.9826,
    lng: -123.6035,
    population: 4000,
    medianHouseholdIncome: 48000,
    populationGrowthPct: 5.1,
    consultingFirmCount: 0,
    smbCount: 53,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 37,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Grays Harbor County seat; timber/ag SMBs, high maturity rate, completely unserved"
  },
  {
    id: "omak",
    name: "Omak",
    county: "Okanogan",
    lat: 48.4115,
    lng: -119.5279,
    population: 5000,
    medianHouseholdIncome: 42000,
    populationGrowthPct: 2.2,
    consultingFirmCount: 0,
    smbCount: 66,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 34,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Okanogan County commerce hub; rodeo/ag/timber SMBs, most populated Okanogan city"
  },
  {
    id: "colville",
    name: "Colville",
    county: "Stevens",
    lat: 48.5451,
    lng: -117.9040,
    population: 5000,
    medianHouseholdIncome: 44000,
    populationGrowthPct: 3.1,
    consultingFirmCount: 0,
    smbCount: 66,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 37,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Stevens County seat; timber/mining adjacent SMBs, completely isolated from consulting firms"
  },
  {
    id: "dayton",
    name: "Dayton",
    county: "Columbia",
    lat: 46.3137,
    lng: -117.9765,
    population: 2500,
    medianHouseholdIncome: 42000,
    populationGrowthPct: -3.1,
    consultingFirmCount: 0,
    smbCount: 40,
    businessMaturityPct: 75,
    ownerAge55PlusPct: 42,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Columbia County seat; oldest Washington city, very high business maturity, no consulting"
  },
  {
    id: "raymond",
    name: "Raymond",
    county: "Pacific",
    lat: 46.6854,
    lng: -123.7334,
    population: 3100,
    medianHouseholdIncome: 44000,
    populationGrowthPct: -2.1,
    consultingFirmCount: 0,
    smbCount: 40,
    businessMaturityPct: 74,
    ownerAge55PlusPct: 40,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Pacific County timber hub; legacy SMBs with succession needs, completely unserved market"
  },
  {
    id: "stevenson",
    name: "Stevenson",
    county: "Skamania",
    lat: 45.6960,
    lng: -121.8892,
    population: 1600,
    medianHouseholdIncome: 48000,
    populationGrowthPct: 5.2,
    consultingFirmCount: 0,
    smbCount: 40,
    businessMaturityPct: 72,
    ownerAge55PlusPct: 38,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Columbia Gorge county seat; outdoor recreation SMBs, highest SMB density in Skamania County"
  },
  {
    id: "forks",
    name: "Forks",
    county: "Clallam",
    lat: 47.9497,
    lng: -124.3879,
    population: 3500,
    medianHouseholdIncome: 42000,
    populationGrowthPct: 2.1,
    consultingFirmCount: 0,
    smbCount: 33,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 35,
    tier: 5,
    estimated: true,
    dataYear: 2021,
    notes: "Olympic Peninsula timber hub; Twilight tourism boost, logging/services SMBs, no consulting"
  }
];

// Metadata for data transparency display
const DATA_METADATA = {
  lastUpdated: "2024-06",
  sources: [
    {
      metric: "Population",
      source: "U.S. Census Bureau, 2020 Decennial Census",
      apiEndpoint: "https://api.census.gov/data/2020/dec/pl",
      updateFrequency: "Every 10 years (ACS 1-yr estimates annually for 65k+ cities)",
      nextUpdate: "2030 Census; ACS annually"
    },
    {
      metric: "Median Household Income",
      source: "ACS 5-Year Estimates 2021, Table B19013",
      apiEndpoint: "https://api.census.gov/data/2021/acs/acs5",
      updateFrequency: "Annually (released Dec each year, ~15-month lag)",
      nextUpdate: "December annually"
    },
    {
      metric: "Population Growth 2010–2020",
      source: "U.S. Census Bureau, Decennial Census comparison",
      apiEndpoint: "https://api.census.gov/data/2020/dec/pl",
      updateFrequency: "Decennial; ACS estimates for interim years",
      nextUpdate: "2030 Census"
    },
    {
      metric: "Consulting Firm Count (NAICS 54161)",
      source: "County Business Patterns 2021 + WA SOS Business Registry (estimated)",
      apiEndpoint: "https://api.census.gov/data/2021/cbp | https://ccfs.sos.wa.gov",
      updateFrequency: "Every 6 months via SOS registry scrape",
      nextUpdate: "Ongoing — schedule API refresh"
    },
    {
      metric: "SMB Count (5–249 employees)",
      source: "County Business Patterns 2021, apportioned by city employment share (estimated)",
      apiEndpoint: "https://api.census.gov/data/2021/cbp",
      updateFrequency: "Annually (CBP released with ~18-month lag)",
      nextUpdate: "CBP 2022 data expected mid-2024"
    },
    {
      metric: "Business Maturity (% 3+ yrs)",
      source: "BLS Business Employment Dynamics survival rates, adjusted by county (estimated)",
      apiEndpoint: "https://www.bls.gov/bdm/",
      updateFrequency: "Annually",
      nextUpdate: "Annual BLS BED release"
    },
    {
      metric: "Owner Age 55+ (%)",
      source: "ACS 5-Year Estimates 2021, Table B01001 (% population 55+)",
      apiEndpoint: "https://api.census.gov/data/2021/acs/acs5",
      updateFrequency: "Every 2 years",
      nextUpdate: "ACS 2023 estimates"
    }
  ]
};

// Export for module use (also works as global in browser)
if (typeof module !== "undefined") {
  module.exports = { CITY_DATA, DATA_METADATA };
}
