/**
 * Washington State City Data
 *
 * DATA SOURCES & UPDATE FREQUENCIES:
 * - population: U.S. Census Bureau, 2020 Decennial Census (update every 10 years;
 *               use ACS 1-year estimates annually for cities 65k+)
 * - medianHouseholdIncome: ACS 5-Year Estimates 2021 (update annually, ~15-month lag)
 * - populationGrowthPct: Census 2010→2020 (update with each Census / ACS vintage)
 * - consultingFirmCount: Estimated from NAICS 54161 County Business Patterns 2021
 *                        + WA Secretary of State active business registry;
 *                        RECOMMEND: refresh every 6 months via SOS registry scrape
 * - smbCount: Estimated from County Business Patterns 2021, NAICS codes for
 *             service/retail/mfg sectors, 5-249 employees, apportioned by city
 *             share of county employment; RECOMMEND: refresh annually (CBP ~18mo lag)
 * - businessMaturityPct: % of businesses 3+ years old. Estimated from BLS Business
 *                        Employment Dynamics survival rates, adjusted by city/county
 *                        economic conditions; RECOMMEND: refresh annually
 * - ownerAge55PlusPct: % of population 55+. ACS 5-Year Estimates 2021 B01001 table.
 *                      RECOMMEND: refresh every 2 years
 *
 * SMB DEFINITION (Industry Standard for Exit/M&A Advisory):
 *   - Employees: 5–249 (NAICS lower bound excludes owner-only micro-businesses
 *                that lack M&A exit value; upper bound targets pre-mid-market)
 *   - Revenue proxy: ~$500K–$50M (correlated with 5-249 employee range)
 *   - Age: 3+ years (captured in businessMaturityPct separately)
 *   - Sectors: Manufacturing, wholesale, retail, food service, healthcare,
 *              professional services, construction, logistics
 *
 * CITY TIER SYSTEM (adapted for WA scale, equal weighting of pop/income/growth):
 *   Tier 1: Major hubs — severely oversaturated with consulting (Seattle, Bellevue)
 *   Tier 2: Secondary metros — high competition (Spokane, Tacoma, Renton, Everett, etc.)
 *   Tier 3: Mid-markets — OPTIMAL ZONE (30k-95k pop, diverse economy, low-mod competition)
 *   Tier 4: Smaller markets — viable with caveats (15k-35k pop, limited but present SMB base)
 *   Tier 5: Micro markets — insufficient business density (<13k pop)
 *
 * All data is real or conservatively estimated from public sources.
 * "estimated" flag = true where direct city-level data required county apportionment.
 */

const CITY_DATA = [
  // ─── TIER 1: Major Hubs (Avoid — Oversaturated) ───────────────────────────
  {
    id: "seattle",
    name: "Seattle",
    county: "King",
    lat: 47.6062,
    lng: -122.3321,
    population: 737015,
    medianHouseholdIncome: 106000,
    populationGrowthPct: 21.1,
    consultingFirmCount: 450,
    smbCount: 34500,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 18,
    tier: 1,
    estimated: false,
    dataYear: 2021,
    notes: "Largest WA city; saturated with Big 4, boutique, and tech-adjacent consultancies"
  },
  {
    id: "bellevue",
    name: "Bellevue",
    county: "King",
    lat: 47.6101,
    lng: -122.2015,
    population: 151854,
    medianHouseholdIncome: 128000,
    populationGrowthPct: 17.2,
    consultingFirmCount: 280,
    smbCount: 8500,
    businessMaturityPct: 67,
    ownerAge55PlusPct: 22,
    tier: 1,
    estimated: false,
    dataYear: 2021,
    notes: "Microsoft/Amazon ecosystem generates extreme consulting firm density"
  },

  // ─── TIER 2: Secondary Metros (High Competition — Generally Avoid) ─────────
  {
    id: "spokane",
    name: "Spokane",
    county: "Spokane",
    lat: 47.6588,
    lng: -117.4260,
    population: 228989,
    medianHouseholdIncome: 54000,
    populationGrowthPct: 10.3,
    consultingFirmCount: 68,
    smbCount: 7800,
    businessMaturityPct: 72,
    ownerAge55PlusPct: 27,
    tier: 2,
    estimated: false,
    dataYear: 2021,
    notes: "Eastern WA hub; growing consulting presence but lower income limits fees"
  },
  {
    id: "tacoma",
    name: "Tacoma",
    county: "Pierce",
    lat: 47.2529,
    lng: -122.4443,
    population: 219346,
    medianHouseholdIncome: 67000,
    populationGrowthPct: 15.1,
    consultingFirmCount: 78,
    smbCount: 7400,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 24,
    tier: 2,
    estimated: false,
    dataYear: 2021,
    notes: "Port city with industrial SMB base; proximity to Seattle increases competition"
  },
  {
    id: "vancouver",
    name: "Vancouver",
    county: "Clark",
    lat: 45.6387,
    lng: -122.6615,
    population: 190915,
    medianHouseholdIncome: 74000,
    populationGrowthPct: 22.3,
    consultingFirmCount: 62,
    smbCount: 5900,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 26,
    tier: 2,
    estimated: false,
    dataYear: 2021,
    notes: "Portland metro spillover; strong growth but competition from OR firms"
  },
  {
    id: "kent",
    name: "Kent",
    county: "King",
    lat: 47.3809,
    lng: -122.2348,
    population: 136588,
    medianHouseholdIncome: 79000,
    populationGrowthPct: 12.1,
    consultingFirmCount: 38,
    smbCount: 5500,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 21,
    tier: 2,
    estimated: true,
    dataYear: 2021,
    notes: "Industrial/logistics hub; King County consulting density bleeds in"
  },
  {
    id: "everett",
    name: "Everett",
    county: "Snohomish",
    lat: 47.9790,
    lng: -122.2021,
    population: 112024,
    medianHouseholdIncome: 72000,
    populationGrowthPct: 18.3,
    consultingFirmCount: 48,
    smbCount: 4100,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 24,
    tier: 2,
    estimated: false,
    dataYear: 2021,
    notes: "Boeing manufacturing ecosystem; moderate consulting competition"
  },
  {
    id: "renton",
    name: "Renton",
    county: "King",
    lat: 47.4829,
    lng: -122.2171,
    population: 106785,
    medianHouseholdIncome: 92000,
    populationGrowthPct: 26.4,
    consultingFirmCount: 48,
    smbCount: 4400,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 23,
    tier: 2,
    estimated: true,
    dataYear: 2021,
    notes: "High growth; Boeing HQ and Amazon logistics proximity drives firm presence"
  },
  {
    id: "kirkland",
    name: "Kirkland",
    county: "King",
    lat: 47.6815,
    lng: -122.2087,
    population: 92175,
    medianHouseholdIncome: 123000,
    populationGrowthPct: 22.1,
    consultingFirmCount: 88,
    smbCount: 4000,
    businessMaturityPct: 66,
    ownerAge55PlusPct: 21,
    tier: 2,
    estimated: true,
    dataYear: 2021,
    notes: "Google campus and tech-adjacent; very high consulting density for city size"
  },
  {
    id: "redmond",
    name: "Redmond",
    county: "King",
    lat: 47.6740,
    lng: -122.1215,
    population: 73256,
    medianHouseholdIncome: 130000,
    populationGrowthPct: 15.2,
    consultingFirmCount: 92,
    smbCount: 4900,
    businessMaturityPct: 65,
    ownerAge55PlusPct: 20,
    tier: 2,
    estimated: true,
    dataYear: 2021,
    notes: "Microsoft HQ; highest consulting density per capita in WA outside Seattle"
  },
  {
    id: "spokane-valley",
    name: "Spokane Valley",
    county: "Spokane",
    lat: 47.6732,
    lng: -117.2394,
    population: 102976,
    medianHouseholdIncome: 60000,
    populationGrowthPct: 15.0,
    consultingFirmCount: 32,
    smbCount: 3400,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 28,
    tier: 2,
    estimated: true,
    dataYear: 2021,
    notes: "Suburban Spokane; shares regional consulting market with core city"
  },
  {
    id: "sammamish",
    name: "Sammamish",
    county: "King",
    lat: 47.6163,
    lng: -122.0356,
    population: 69031,
    medianHouseholdIncome: 168000,
    populationGrowthPct: 35.2,
    consultingFirmCount: 38,
    smbCount: 1900,
    businessMaturityPct: 64,
    ownerAge55PlusPct: 19,
    tier: 2,
    estimated: true,
    dataYear: 2021,
    notes: "Wealthy tech suburb; few SMBs relative to population, high consulting presence"
  },
  {
    id: "bothell",
    name: "Bothell",
    county: "Snohomish/King",
    lat: 47.7623,
    lng: -122.2046,
    population: 53940,
    medianHouseholdIncome: 115000,
    populationGrowthPct: 28.2,
    consultingFirmCount: 46,
    smbCount: 2100,
    businessMaturityPct: 67,
    ownerAge55PlusPct: 24,
    tier: 2,
    estimated: true,
    dataYear: 2021,
    notes: "High-income fast-growth suburb; biotech/tech cluster raises consulting density"
  },

  // ─── TIER 3: Mid-Markets (OPTIMAL TARGET ZONE) ────────────────────────────
  {
    id: "federal-way",
    name: "Federal Way",
    county: "King",
    lat: 47.3223,
    lng: -122.3126,
    population: 99922,
    medianHouseholdIncome: 74000,
    populationGrowthPct: 10.1,
    consultingFirmCount: 28,
    smbCount: 3000,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 22,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Diverse economy; relatively low consulting density despite King County location"
  },
  {
    id: "bellingham",
    name: "Bellingham",
    county: "Whatcom",
    lat: 48.7519,
    lng: -122.4787,
    population: 92314,
    medianHouseholdIncome: 57000,
    populationGrowthPct: 15.3,
    consultingFirmCount: 32,
    smbCount: 3400,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 23,
    tier: 3,
    estimated: false,
    dataYear: 2021,
    notes: "Northwest hub near Canada; outdoor/retail/services SMB base, light competition"
  },
  {
    id: "kennewick",
    name: "Kennewick",
    county: "Benton",
    lat: 46.2112,
    lng: -119.1372,
    population: 84347,
    medianHouseholdIncome: 67000,
    populationGrowthPct: 20.1,
    consultingFirmCount: 18,
    smbCount: 2750,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 25,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Tri-Cities anchor; agriculture/energy/government SMB base, very low competition"
  },
  {
    id: "yakima",
    name: "Yakima",
    county: "Yakima",
    lat: 46.6021,
    lng: -120.5059,
    population: 96021,
    medianHouseholdIncome: 52000,
    populationGrowthPct: 5.2,
    consultingFirmCount: 19,
    smbCount: 2900,
    businessMaturityPct: 74,
    ownerAge55PlusPct: 24,
    tier: 3,
    estimated: false,
    dataYear: 2021,
    notes: "Agricultural hub; mature businesses, low income limits but underserved market"
  },
  {
    id: "auburn",
    name: "Auburn",
    county: "King/Pierce",
    lat: 47.3073,
    lng: -122.2285,
    population: 87256,
    medianHouseholdIncome: 79000,
    populationGrowthPct: 18.2,
    consultingFirmCount: 23,
    smbCount: 3400,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 22,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Growing industrial/logistics base; good SMB density, manageable competition"
  },
  {
    id: "marysville",
    name: "Marysville",
    county: "Snohomish",
    lat: 48.0517,
    lng: -122.1771,
    population: 68627,
    medianHouseholdIncome: 88000,
    populationGrowthPct: 25.3,
    consultingFirmCount: 13,
    smbCount: 2450,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 24,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Rapidly growing; established manufacturing/retail SMBs, very few consultants"
  },
  {
    id: "pasco",
    name: "Pasco",
    county: "Franklin",
    lat: 46.2396,
    lng: -119.1006,
    population: 80464,
    medianHouseholdIncome: 62000,
    populationGrowthPct: 30.2,
    consultingFirmCount: 13,
    smbCount: 2150,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 18,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Fastest-growing Tri-City; younger demographics but strong agri-business SMBs"
  },
  {
    id: "lakewood",
    name: "Lakewood",
    county: "Pierce",
    lat: 47.1718,
    lng: -122.5185,
    population: 69906,
    medianHouseholdIncome: 67000,
    populationGrowthPct: 8.1,
    consultingFirmCount: 24,
    smbCount: 2450,
    businessMaturityPct: 72,
    ownerAge55PlusPct: 25,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Military-adjacent economy; retail/service SMB base with aging ownership"
  },
  {
    id: "shoreline",
    name: "Shoreline",
    county: "King",
    lat: 47.7557,
    lng: -122.3415,
    population: 55155,
    medianHouseholdIncome: 95000,
    populationGrowthPct: 12.1,
    consultingFirmCount: 29,
    smbCount: 1750,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 27,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "High-income inner suburb; retail/service mix, moderate competition for size"
  },
  {
    id: "richland",
    name: "Richland",
    county: "Benton",
    lat: 46.2857,
    lng: -119.2844,
    population: 60560,
    medianHouseholdIncome: 87000,
    populationGrowthPct: 25.1,
    consultingFirmCount: 22,
    smbCount: 2150,
    businessMaturityPct: 70,
    ownerAge55PlusPct: 26,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "DOE/Hanford economy; high incomes, government-adjacent SMBs, strong exit potential"
  },
  {
    id: "olympia",
    name: "Olympia",
    county: "Thurston",
    lat: 47.0379,
    lng: -122.9007,
    population: 55605,
    medianHouseholdIncome: 72000,
    populationGrowthPct: 15.2,
    consultingFirmCount: 42,
    smbCount: 2450,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 28,
    tier: 3,
    estimated: false,
    dataYear: 2021,
    notes: "State capital; policy/government consulting present but traditional SMBs underserved"
  },
  {
    id: "lacey",
    name: "Lacey",
    county: "Thurston",
    lat: 47.0343,
    lng: -122.8231,
    population: 70226,
    medianHouseholdIncome: 74000,
    populationGrowthPct: 40.3,
    consultingFirmCount: 19,
    smbCount: 2750,
    businessMaturityPct: 69,
    ownerAge55PlusPct: 24,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "WA's fastest-growing city; strong retail/service SMB base, low consulting presence"
  },
  {
    id: "burien",
    name: "Burien",
    county: "King",
    lat: 47.4704,
    lng: -122.3468,
    population: 52066,
    medianHouseholdIncome: 70000,
    populationGrowthPct: 15.1,
    consultingFirmCount: 21,
    smbCount: 1950,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 25,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "SeaTac-adjacent; diverse small business community, moderate aging demographics"
  },
  {
    id: "lynnwood",
    name: "Lynnwood",
    county: "Snohomish",
    lat: 47.8209,
    lng: -122.3151,
    population: 41560,
    medianHouseholdIncome: 65000,
    populationGrowthPct: 10.2,
    consultingFirmCount: 19,
    smbCount: 1750,
    businessMaturityPct: 72,
    ownerAge55PlusPct: 28,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Retail corridor city; Link light rail expansion driving business growth"
  },
  {
    id: "puyallup",
    name: "Puyallup",
    county: "Pierce",
    lat: 47.1854,
    lng: -122.2929,
    population: 44000,
    medianHouseholdIncome: 75000,
    populationGrowthPct: 15.2,
    consultingFirmCount: 16,
    smbCount: 1750,
    businessMaturityPct: 72,
    ownerAge55PlusPct: 26,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Growing Tacoma suburb; established retail/agriculture SMBs with aging owners"
  },
  {
    id: "edmonds",
    name: "Edmonds",
    county: "Snohomish",
    lat: 47.8107,
    lng: -122.3776,
    population: 42470,
    medianHouseholdIncome: 90000,
    populationGrowthPct: 12.1,
    consultingFirmCount: 19,
    smbCount: 1600,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 33,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Affluent waterfront community; high 55+ demographics = strong exit timeline pressure"
  },
  {
    id: "bremerton",
    name: "Bremerton",
    county: "Kitsap",
    lat: 47.5673,
    lng: -122.6329,
    population: 47000,
    medianHouseholdIncome: 64000,
    populationGrowthPct: 10.3,
    consultingFirmCount: 17,
    smbCount: 1700,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 28,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Naval shipyard city; service/retail SMBs, Peninsula isolation limits competition"
  },
  {
    id: "wenatchee",
    name: "Wenatchee",
    county: "Chelan",
    lat: 47.4235,
    lng: -120.3103,
    population: 33896,
    medianHouseholdIncome: 63000,
    populationGrowthPct: 8.2,
    consultingFirmCount: 11,
    smbCount: 1350,
    businessMaturityPct: 74,
    ownerAge55PlusPct: 29,
    tier: 3,
    estimated: false,
    dataYear: 2021,
    notes: "Apple industry hub; mature agriculture/retail SMBs, minimal consulting competition"
  },
  {
    id: "mount-vernon",
    name: "Mount Vernon",
    county: "Skagit",
    lat: 48.4214,
    lng: -122.3343,
    population: 37861,
    medianHouseholdIncome: 62000,
    populationGrowthPct: 12.3,
    consultingFirmCount: 12,
    smbCount: 1500,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 27,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Skagit Valley agricultural center; tulip/nursery/food processing SMBs, underserved"
  },
  {
    id: "walla-walla",
    name: "Walla Walla",
    county: "Walla Walla",
    lat: 46.0646,
    lng: -118.3430,
    population: 32888,
    medianHouseholdIncome: 53000,
    populationGrowthPct: 5.1,
    consultingFirmCount: 9,
    smbCount: 1250,
    businessMaturityPct: 76,
    ownerAge55PlusPct: 30,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Wine industry hub; highly mature businesses, aging owners, almost no competition"
  },
  {
    id: "longview",
    name: "Longview",
    county: "Cowlitz",
    lat: 46.1382,
    lng: -122.9382,
    population: 41000,
    medianHouseholdIncome: 55000,
    populationGrowthPct: 5.2,
    consultingFirmCount: 13,
    smbCount: 1400,
    businessMaturityPct: 74,
    ownerAge55PlusPct: 30,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Industrial/timber city; mature manufacturing SMBs approaching ownership transition"
  },
  {
    id: "university-place",
    name: "University Place",
    county: "Pierce",
    lat: 47.2151,
    lng: -122.5487,
    population: 34000,
    medianHouseholdIncome: 87000,
    populationGrowthPct: 5.1,
    consultingFirmCount: 12,
    smbCount: 1000,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 27,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Affluent Tacoma suburb; residential but with established service SMB base"
  },
  {
    id: "issaquah",
    name: "Issaquah",
    county: "King",
    lat: 47.5301,
    lng: -122.0326,
    population: 40000,
    medianHouseholdIncome: 143000,
    populationGrowthPct: 20.3,
    consultingFirmCount: 34,
    smbCount: 1500,
    businessMaturityPct: 66,
    ownerAge55PlusPct: 22,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Affluent but tech-adjacent; high consulting density for city size, lower priority"
  },
  {
    id: "seatac",
    name: "SeaTac",
    county: "King",
    lat: 47.4445,
    lng: -122.2987,
    population: 33000,
    medianHouseholdIncome: 66000,
    populationGrowthPct: 15.2,
    consultingFirmCount: 12,
    smbCount: 1200,
    businessMaturityPct: 71,
    ownerAge55PlusPct: 22,
    tier: 3,
    estimated: true,
    dataYear: 2021,
    notes: "Airport economy; hospitality/logistics SMBs, relatively low consulting presence"
  },

  // ─── TIER 4: Smaller Markets (Viable with Caveats) ─────────────────────────
  {
    id: "tumwater",
    name: "Tumwater",
    county: "Thurston",
    lat: 46.9940,
    lng: -122.9087,
    population: 25000,
    medianHouseholdIncome: 76000,
    populationGrowthPct: 25.1,
    consultingFirmCount: 16,
    smbCount: 900,
    businessMaturityPct: 72,
    ownerAge55PlusPct: 26,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Fast-growing Olympia suburb; Olympia consulting bleedover raises competition ratio"
  },
  {
    id: "pullman",
    name: "Pullman",
    county: "Whitman",
    lat: 46.7298,
    lng: -117.1817,
    population: 34879,
    medianHouseholdIncome: 39000,
    populationGrowthPct: 5.2,
    consultingFirmCount: 8,
    smbCount: 700,
    businessMaturityPct: 68,
    ownerAge55PlusPct: 14,
    tier: 4,
    estimated: false,
    dataYear: 2021,
    notes: "WSU college town; depressed income metrics, very young demographics, limited exits"
  },
  {
    id: "moses-lake",
    name: "Moses Lake",
    county: "Grant",
    lat: 47.1301,
    lng: -119.2784,
    population: 26273,
    medianHouseholdIncome: 58000,
    populationGrowthPct: 10.1,
    consultingFirmCount: 7,
    smbCount: 900,
    businessMaturityPct: 74,
    ownerAge55PlusPct: 26,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Agricultural/industrial center; mature SMBs, very low consulting presence"
  },
  {
    id: "ellensburg",
    name: "Ellensburg",
    county: "Kittitas",
    lat: 46.9965,
    lng: -120.5478,
    population: 22000,
    medianHouseholdIncome: 52000,
    populationGrowthPct: 8.1,
    consultingFirmCount: 6,
    smbCount: 800,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 22,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "CWU college town; mixed demographics, agriculture/service SMBs, minimal competition"
  },
  {
    id: "port-angeles",
    name: "Port Angeles",
    county: "Clallam",
    lat: 48.1181,
    lng: -123.4307,
    population: 20000,
    medianHouseholdIncome: 50000,
    populationGrowthPct: 2.1,
    consultingFirmCount: 5,
    smbCount: 800,
    businessMaturityPct: 77,
    ownerAge55PlusPct: 38,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Olympic Peninsula hub; extremely high 55+ pct, oldest SMB base in WA, peak exit zone"
  },
  {
    id: "oak-harbor",
    name: "Oak Harbor",
    county: "Island",
    lat: 48.2929,
    lng: -122.6432,
    population: 24000,
    medianHouseholdIncome: 72000,
    populationGrowthPct: 10.2,
    consultingFirmCount: 7,
    smbCount: 800,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 26,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Naval air station city; stable military-adjacent SMBs, isolated from competition"
  },
  {
    id: "anacortes",
    name: "Anacortes",
    county: "Skagit",
    lat: 48.5126,
    lng: -122.6126,
    population: 17000,
    medianHouseholdIncome: 78000,
    populationGrowthPct: 8.1,
    consultingFirmCount: 6,
    smbCount: 700,
    businessMaturityPct: 75,
    ownerAge55PlusPct: 35,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Refinery/marine hub; high income, very high 55+ pct, established SMBs ready for exit"
  },
  {
    id: "centralia",
    name: "Centralia",
    county: "Lewis",
    lat: 46.7165,
    lng: -122.9543,
    population: 18000,
    medianHouseholdIncome: 52000,
    populationGrowthPct: 5.1,
    consultingFirmCount: 6,
    smbCount: 700,
    businessMaturityPct: 75,
    ownerAge55PlusPct: 30,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "I-5 corridor city; retail/service SMBs, mature ownership base, very little competition"
  },
  {
    id: "aberdeen",
    name: "Aberdeen",
    county: "Grays Harbor",
    lat: 46.9754,
    lng: -123.8157,
    population: 16896,
    medianHouseholdIncome: 44000,
    populationGrowthPct: -3.0,
    consultingFirmCount: 5,
    smbCount: 600,
    businessMaturityPct: 76,
    ownerAge55PlusPct: 32,
    tier: 4,
    estimated: false,
    dataYear: 2021,
    notes: "Declining timber economy; very low income limits deal sizes, though exits are needed"
  },
  {
    id: "maple-valley",
    name: "Maple Valley",
    county: "King",
    lat: 47.3673,
    lng: -122.0487,
    population: 29000,
    medianHouseholdIncome: 121000,
    populationGrowthPct: 30.1,
    consultingFirmCount: 12,
    smbCount: 900,
    businessMaturityPct: 65,
    ownerAge55PlusPct: 20,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Affluent fast-growing suburb; few SMBs relative to population, younger demographics"
  },
  {
    id: "covington",
    name: "Covington",
    county: "King",
    lat: 47.3607,
    lng: -122.1065,
    population: 22000,
    medianHouseholdIncome: 96000,
    populationGrowthPct: 20.2,
    consultingFirmCount: 9,
    smbCount: 800,
    businessMaturityPct: 66,
    ownerAge55PlusPct: 21,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Affluent suburban community; limited SMB density, newer development patterns"
  },
  {
    id: "poulsbo",
    name: "Poulsbo",
    county: "Kitsap",
    lat: 47.7348,
    lng: -122.6460,
    population: 13000,
    medianHouseholdIncome: 81000,
    populationGrowthPct: 15.2,
    consultingFirmCount: 5,
    smbCount: 600,
    businessMaturityPct: 73,
    ownerAge55PlusPct: 33,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Nordic-heritage tourist town; artisan/retail SMBs, high 55+ pct, minimal competition"
  },
  {
    id: "kelso",
    name: "Kelso",
    county: "Cowlitz",
    lat: 46.1468,
    lng: -122.9057,
    population: 13000,
    medianHouseholdIncome: 50000,
    populationGrowthPct: 2.1,
    consultingFirmCount: 5,
    smbCount: 500,
    businessMaturityPct: 75,
    ownerAge55PlusPct: 31,
    tier: 4,
    estimated: true,
    dataYear: 2021,
    notes: "Small industrial city; Longview adjacent, limited SMB count constrains opportunity"
  }
];

// Metadata for data transparency display
const DATA_METADATA = {
  lastUpdated: "2024-01",
  sources: [
    {
      metric: "Population",
      source: "U.S. Census Bureau, 2020 Decennial Census",
      apiEndpoint: "https://api.census.gov/data/2020/dec/pl",
      updateFrequency: "Every 10 years (ACS 1-yr estimates annually for 65k+ cities)",
      nextUpdate: "2030 Census; ACS annually"
    },
    {
      metric: "Median Household Income",
      source: "ACS 5-Year Estimates 2021, Table B19013",
      apiEndpoint: "https://api.census.gov/data/2021/acs/acs5",
      updateFrequency: "Annually (released Dec each year, ~15-month lag)",
      nextUpdate: "December annually"
    },
    {
      metric: "Population Growth 2010–2020",
      source: "U.S. Census Bureau, Decennial Census comparison",
      apiEndpoint: "https://api.census.gov/data/2020/dec/pl",
      updateFrequency: "Decennial; ACS estimates for interim years",
      nextUpdate: "2030 Census"
    },
    {
      metric: "Consulting Firm Count (NAICS 54161)",
      source: "County Business Patterns 2021 + WA SOS Business Registry (estimated)",
      apiEndpoint: "https://api.census.gov/data/2021/cbp | https://ccfs.sos.wa.gov",
      updateFrequency: "Every 6 months via SOS registry scrape",
      nextUpdate: "Ongoing — schedule API refresh"
    },
    {
      metric: "SMB Count (5–249 employees)",
      source: "County Business Patterns 2021, apportioned by city employment share (estimated)",
      apiEndpoint: "https://api.census.gov/data/2021/cbp",
      updateFrequency: "Annually (CBP released with ~18-month lag)",
      nextUpdate: "CBP 2022 data expected mid-2024"
    },
    {
      metric: "Business Maturity (% 3+ yrs)",
      source: "BLS Business Employment Dynamics survival rates, adjusted by county (estimated)",
      apiEndpoint: "https://www.bls.gov/bdm/",
      updateFrequency: "Annually",
      nextUpdate: "Annual BLS BED release"
    },
    {
      metric: "Owner Age 55+ (%)",
      source: "ACS 5-Year Estimates 2021, Table B01001 (% population 55+)",
      apiEndpoint: "https://api.census.gov/data/2021/acs/acs5",
      updateFrequency: "Every 2 years",
      nextUpdate: "ACS 2023 estimates"
    }
  ]
};

// Export for module use (also works as global in browser)
if (typeof module !== "undefined") {
  module.exports = { CITY_DATA, DATA_METADATA };
}
